/* automatically generated by rust-bindgen */

pub const AL_INVALID: ::std::os::raw::c_int = -1;
pub const AL_NONE: ::std::os::raw::c_uint = 0;
pub const AL_FALSE: ::std::os::raw::c_uint = 0;
pub const AL_TRUE: ::std::os::raw::c_uint = 1;
pub const AL_SOURCE_RELATIVE: ::std::os::raw::c_uint = 514;
pub const AL_CONE_INNER_ANGLE: ::std::os::raw::c_uint = 4097;
pub const AL_CONE_OUTER_ANGLE: ::std::os::raw::c_uint = 4098;
pub const AL_PITCH: ::std::os::raw::c_uint = 4099;
pub const AL_POSITION: ::std::os::raw::c_uint = 4100;
pub const AL_DIRECTION: ::std::os::raw::c_uint = 4101;
pub const AL_VELOCITY: ::std::os::raw::c_uint = 4102;
pub const AL_LOOPING: ::std::os::raw::c_uint = 4103;
pub const AL_BUFFER: ::std::os::raw::c_uint = 4105;
pub const AL_GAIN: ::std::os::raw::c_uint = 4106;
pub const AL_MIN_GAIN: ::std::os::raw::c_uint = 4109;
pub const AL_MAX_GAIN: ::std::os::raw::c_uint = 4110;
pub const AL_ORIENTATION: ::std::os::raw::c_uint = 4111;
pub const AL_SOURCE_STATE: ::std::os::raw::c_uint = 4112;
pub const AL_INITIAL: ::std::os::raw::c_uint = 4113;
pub const AL_PLAYING: ::std::os::raw::c_uint = 4114;
pub const AL_PAUSED: ::std::os::raw::c_uint = 4115;
pub const AL_STOPPED: ::std::os::raw::c_uint = 4116;
pub const AL_BUFFERS_QUEUED: ::std::os::raw::c_uint = 4117;
pub const AL_BUFFERS_PROCESSED: ::std::os::raw::c_uint = 4118;
pub const AL_REFERENCE_DISTANCE: ::std::os::raw::c_uint = 4128;
pub const AL_ROLLOFF_FACTOR: ::std::os::raw::c_uint = 4129;
pub const AL_CONE_OUTER_GAIN: ::std::os::raw::c_uint = 4130;
pub const AL_MAX_DISTANCE: ::std::os::raw::c_uint = 4131;
pub const AL_SEC_OFFSET: ::std::os::raw::c_uint = 4132;
pub const AL_SAMPLE_OFFSET: ::std::os::raw::c_uint = 4133;
pub const AL_BYTE_OFFSET: ::std::os::raw::c_uint = 4134;
pub const AL_SOURCE_TYPE: ::std::os::raw::c_uint = 4135;
pub const AL_STATIC: ::std::os::raw::c_uint = 4136;
pub const AL_STREAMING: ::std::os::raw::c_uint = 4137;
pub const AL_UNDETERMINED: ::std::os::raw::c_uint = 4144;
pub const AL_FORMAT_MONO8: ::std::os::raw::c_uint = 4352;
pub const AL_FORMAT_MONO16: ::std::os::raw::c_uint = 4353;
pub const AL_FORMAT_STEREO8: ::std::os::raw::c_uint = 4354;
pub const AL_FORMAT_STEREO16: ::std::os::raw::c_uint = 4355;
pub const AL_FREQUENCY: ::std::os::raw::c_uint = 8193;
pub const AL_BITS: ::std::os::raw::c_uint = 8194;
pub const AL_CHANNELS: ::std::os::raw::c_uint = 8195;
pub const AL_SIZE: ::std::os::raw::c_uint = 8196;
pub const AL_UNUSED: ::std::os::raw::c_uint = 8208;
pub const AL_PENDING: ::std::os::raw::c_uint = 8209;
pub const AL_PROCESSED: ::std::os::raw::c_uint = 8210;
pub const AL_NO_ERROR: ::std::os::raw::c_uint = 0;
pub const AL_INVALID_NAME: ::std::os::raw::c_uint = 40961;
pub const AL_INVALID_ENUM: ::std::os::raw::c_uint = 40962;
pub const AL_INVALID_VALUE: ::std::os::raw::c_uint = 40963;
pub const AL_INVALID_OPERATION: ::std::os::raw::c_uint = 40964;
pub const AL_OUT_OF_MEMORY: ::std::os::raw::c_uint = 40965;
pub const AL_VENDOR: ::std::os::raw::c_uint = 45057;
pub const AL_VERSION: ::std::os::raw::c_uint = 45058;
pub const AL_RENDERER: ::std::os::raw::c_uint = 45059;
pub const AL_EXTENSIONS: ::std::os::raw::c_uint = 45060;
pub const AL_INVERSE_DISTANCE: ::std::os::raw::c_uint = 53249;
pub const AL_INVERSE_DISTANCE_CLAMPED: ::std::os::raw::c_uint = 53250;
pub const AL_LINEAR_DISTANCE: ::std::os::raw::c_uint = 53251;
pub const AL_LINEAR_DISTANCE_CLAMPED: ::std::os::raw::c_uint = 53252;
pub const AL_EXPONENT_DISTANCE: ::std::os::raw::c_uint = 53253;
pub const AL_EXPONENT_DISTANCE_CLAMPED: ::std::os::raw::c_uint = 53254;
/** 8-bit boolean */
pub type ALboolean = ::std::os::raw::c_char;
/** character */
pub type ALchar = ::std::os::raw::c_char;
/** signed 8-bit 2's complement integer */
pub type ALbyte = ::std::os::raw::c_schar;
/** unsigned 8-bit integer */
pub type ALubyte = ::std::os::raw::c_uchar;
/** signed 16-bit 2's complement integer */
pub type ALshort = ::std::os::raw::c_short;
/** unsigned 16-bit integer */
pub type ALushort = ::std::os::raw::c_ushort;
/** signed 32-bit 2's complement integer */
pub type ALint = ::std::os::raw::c_int;
/** unsigned 32-bit integer */
pub type ALuint = ::std::os::raw::c_uint;
/** non-negative 32-bit binary integer size */
pub type ALsizei = ::std::os::raw::c_int;
/** enumerated 32-bit value */
pub type ALenum = ::std::os::raw::c_int;
/** 32-bit IEEE754 floating-point */
pub type ALfloat = f32;
/** 64-bit IEEE754 floating-point */
pub type ALdouble = f64;
/** void type (for opaque pointers only) */
pub type ALvoid = ::std::os::raw::c_void;
extern "C" {
    pub fn alDopplerFactor(value: ALfloat);
}
extern "C" {
    pub fn alDopplerVelocity(value: ALfloat);
}
extern "C" {
    pub fn alSpeedOfSound(value: ALfloat);
}
extern "C" {
    pub fn alDistanceModel(distanceModel: ALenum);
}
extern "C" {
    /** Renderer State management. */
    pub fn alEnable(capability: ALenum);
}
extern "C" {
    pub fn alDisable(capability: ALenum);
}
extern "C" {
    pub fn alIsEnabled(capability: ALenum) -> ALboolean;
}
extern "C" {
    /** State retrieval. */
    pub fn alGetString(param: ALenum) -> *const ALchar;
}
extern "C" {
    pub fn alGetBooleanv(param: ALenum, values: *mut ALboolean);
}
extern "C" {
    pub fn alGetIntegerv(param: ALenum, values: *mut ALint);
}
extern "C" {
    pub fn alGetFloatv(param: ALenum, values: *mut ALfloat);
}
extern "C" {
    pub fn alGetDoublev(param: ALenum, values: *mut ALdouble);
}
extern "C" {
    pub fn alGetBoolean(param: ALenum) -> ALboolean;
}
extern "C" {
    pub fn alGetInteger(param: ALenum) -> ALint;
}
extern "C" {
    pub fn alGetFloat(param: ALenum) -> ALfloat;
}
extern "C" {
    pub fn alGetDouble(param: ALenum) -> ALdouble;
}
extern "C" {
    /**
 * Error retrieval.
 *
 * Obtain the first error generated in the AL context since the last check.
 */
    pub fn alGetError() -> ALenum;
}
extern "C" {
    /**
 * Extension support.
 *
 * Query for the presence of an extension, and obtain any appropriate function
 * pointers and enum values.
 */
    pub fn alIsExtensionPresent(extname: *const ALchar) -> ALboolean;
}
extern "C" {
    pub fn alGetProcAddress(fname: *const ALchar)
     -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn alGetEnumValue(ename: *const ALchar) -> ALenum;
}
extern "C" {
    /** Set Listener parameters */
    pub fn alListenerf(param: ALenum, value: ALfloat);
}
extern "C" {
    pub fn alListener3f(param: ALenum, value1: ALfloat, value2: ALfloat,
                        value3: ALfloat);
}
extern "C" {
    pub fn alListenerfv(param: ALenum, values: *const ALfloat);
}
extern "C" {
    pub fn alListeneri(param: ALenum, value: ALint);
}
extern "C" {
    pub fn alListener3i(param: ALenum, value1: ALint, value2: ALint,
                        value3: ALint);
}
extern "C" {
    pub fn alListeneriv(param: ALenum, values: *const ALint);
}
extern "C" {
    /** Get Listener parameters */
    pub fn alGetListenerf(param: ALenum, value: *mut ALfloat);
}
extern "C" {
    pub fn alGetListener3f(param: ALenum, value1: *mut ALfloat,
                           value2: *mut ALfloat, value3: *mut ALfloat);
}
extern "C" {
    pub fn alGetListenerfv(param: ALenum, values: *mut ALfloat);
}
extern "C" {
    pub fn alGetListeneri(param: ALenum, value: *mut ALint);
}
extern "C" {
    pub fn alGetListener3i(param: ALenum, value1: *mut ALint,
                           value2: *mut ALint, value3: *mut ALint);
}
extern "C" {
    pub fn alGetListeneriv(param: ALenum, values: *mut ALint);
}
extern "C" {
    /** Create Source objects. */
    pub fn alGenSources(n: ALsizei, sources: *mut ALuint);
}
extern "C" {
    /** Delete Source objects. */
    pub fn alDeleteSources(n: ALsizei, sources: *const ALuint);
}
extern "C" {
    /** Verify a handle is a valid Source. */
    pub fn alIsSource(source: ALuint) -> ALboolean;
}
extern "C" {
    /** Set Source parameters. */
    pub fn alSourcef(source: ALuint, param: ALenum, value: ALfloat);
}
extern "C" {
    pub fn alSource3f(source: ALuint, param: ALenum, value1: ALfloat,
                      value2: ALfloat, value3: ALfloat);
}
extern "C" {
    pub fn alSourcefv(source: ALuint, param: ALenum, values: *const ALfloat);
}
extern "C" {
    pub fn alSourcei(source: ALuint, param: ALenum, value: ALint);
}
extern "C" {
    pub fn alSource3i(source: ALuint, param: ALenum, value1: ALint,
                      value2: ALint, value3: ALint);
}
extern "C" {
    pub fn alSourceiv(source: ALuint, param: ALenum, values: *const ALint);
}
extern "C" {
    /** Get Source parameters. */
    pub fn alGetSourcef(source: ALuint, param: ALenum, value: *mut ALfloat);
}
extern "C" {
    pub fn alGetSource3f(source: ALuint, param: ALenum, value1: *mut ALfloat,
                         value2: *mut ALfloat, value3: *mut ALfloat);
}
extern "C" {
    pub fn alGetSourcefv(source: ALuint, param: ALenum, values: *mut ALfloat);
}
extern "C" {
    pub fn alGetSourcei(source: ALuint, param: ALenum, value: *mut ALint);
}
extern "C" {
    pub fn alGetSource3i(source: ALuint, param: ALenum, value1: *mut ALint,
                         value2: *mut ALint, value3: *mut ALint);
}
extern "C" {
    pub fn alGetSourceiv(source: ALuint, param: ALenum, values: *mut ALint);
}
extern "C" {
    /** Play, replay, or resume (if paused) a list of Sources */
    pub fn alSourcePlayv(n: ALsizei, sources: *const ALuint);
}
extern "C" {
    /** Stop a list of Sources */
    pub fn alSourceStopv(n: ALsizei, sources: *const ALuint);
}
extern "C" {
    /** Rewind a list of Sources */
    pub fn alSourceRewindv(n: ALsizei, sources: *const ALuint);
}
extern "C" {
    /** Pause a list of Sources */
    pub fn alSourcePausev(n: ALsizei, sources: *const ALuint);
}
extern "C" {
    /** Play, replay, or resume a Source */
    pub fn alSourcePlay(source: ALuint);
}
extern "C" {
    /** Stop a Source */
    pub fn alSourceStop(source: ALuint);
}
extern "C" {
    /** Rewind a Source (set playback postiton to beginning) */
    pub fn alSourceRewind(source: ALuint);
}
extern "C" {
    /** Pause a Source */
    pub fn alSourcePause(source: ALuint);
}
extern "C" {
    /** Queue buffers onto a source */
    pub fn alSourceQueueBuffers(source: ALuint, nb: ALsizei,
                                buffers: *const ALuint);
}
extern "C" {
    /** Unqueue processed buffers from a source */
    pub fn alSourceUnqueueBuffers(source: ALuint, nb: ALsizei,
                                  buffers: *mut ALuint);
}
extern "C" {
    /** Create Buffer objects */
    pub fn alGenBuffers(n: ALsizei, buffers: *mut ALuint);
}
extern "C" {
    /** Delete Buffer objects */
    pub fn alDeleteBuffers(n: ALsizei, buffers: *const ALuint);
}
extern "C" {
    /** Verify a handle is a valid Buffer */
    pub fn alIsBuffer(buffer: ALuint) -> ALboolean;
}
extern "C" {
    /** Specifies the data to be copied into a buffer */
    pub fn alBufferData(buffer: ALuint, format: ALenum, data: *const ALvoid,
                        size: ALsizei, freq: ALsizei);
}
extern "C" {
    /** Set Buffer parameters, */
    pub fn alBufferf(buffer: ALuint, param: ALenum, value: ALfloat);
}
extern "C" {
    pub fn alBuffer3f(buffer: ALuint, param: ALenum, value1: ALfloat,
                      value2: ALfloat, value3: ALfloat);
}
extern "C" {
    pub fn alBufferfv(buffer: ALuint, param: ALenum, values: *const ALfloat);
}
extern "C" {
    pub fn alBufferi(buffer: ALuint, param: ALenum, value: ALint);
}
extern "C" {
    pub fn alBuffer3i(buffer: ALuint, param: ALenum, value1: ALint,
                      value2: ALint, value3: ALint);
}
extern "C" {
    pub fn alBufferiv(buffer: ALuint, param: ALenum, values: *const ALint);
}
extern "C" {
    /** Get Buffer parameters. */
    pub fn alGetBufferf(buffer: ALuint, param: ALenum, value: *mut ALfloat);
}
extern "C" {
    pub fn alGetBuffer3f(buffer: ALuint, param: ALenum, value1: *mut ALfloat,
                         value2: *mut ALfloat, value3: *mut ALfloat);
}
extern "C" {
    pub fn alGetBufferfv(buffer: ALuint, param: ALenum, values: *mut ALfloat);
}
extern "C" {
    pub fn alGetBufferi(buffer: ALuint, param: ALenum, value: *mut ALint);
}
extern "C" {
    pub fn alGetBuffer3i(buffer: ALuint, param: ALenum, value1: *mut ALint,
                         value2: *mut ALint, value3: *mut ALint);
}
extern "C" {
    pub fn alGetBufferiv(buffer: ALuint, param: ALenum, values: *mut ALint);
}
/** Pointer-to-function type, useful for dynamically getting AL entry points. */
pub type LPALENABLE =
    ::std::option::Option<unsafe extern "C" fn(capability: ALenum)>;
pub type LPALDISABLE =
    ::std::option::Option<unsafe extern "C" fn(capability: ALenum)>;
pub type LPALISENABLED =
    ::std::option::Option<unsafe extern "C" fn(capability: ALenum)
                              -> ALboolean>;
pub type LPALGETSTRING =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum)
                              -> *const ALchar>;
pub type LPALGETBOOLEANV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               values: *mut ALboolean)>;
pub type LPALGETINTEGERV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               values: *mut ALint)>;
pub type LPALGETFLOATV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               values: *mut ALfloat)>;
pub type LPALGETDOUBLEV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               values: *mut ALdouble)>;
pub type LPALGETBOOLEAN =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum) -> ALboolean>;
pub type LPALGETINTEGER =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum) -> ALint>;
pub type LPALGETFLOAT =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum) -> ALfloat>;
pub type LPALGETDOUBLE =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum) -> ALdouble>;
pub type LPALGETERROR =
    ::std::option::Option<unsafe extern "C" fn() -> ALenum>;
pub type LPALISEXTENSIONPRESENT =
    ::std::option::Option<unsafe extern "C" fn(extname: *const ALchar)
                              -> ALboolean>;
pub type LPALGETPROCADDRESS =
    ::std::option::Option<unsafe extern "C" fn(fname: *const ALchar)
                              -> *mut ::std::os::raw::c_void>;
pub type LPALGETENUMVALUE =
    ::std::option::Option<unsafe extern "C" fn(ename: *const ALchar)
                              -> ALenum>;
pub type LPALLISTENERF =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               value: ALfloat)>;
pub type LPALLISTENER3F =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum, value1: ALfloat,
                                               value2: ALfloat,
                                               value3: ALfloat)>;
pub type LPALLISTENERFV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               values: *const ALfloat)>;
pub type LPALLISTENERI =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum, value: ALint)>;
pub type LPALLISTENER3I =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum, value1: ALint,
                                               value2: ALint, value3: ALint)>;
pub type LPALLISTENERIV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               values: *const ALint)>;
pub type LPALGETLISTENERF =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               value: *mut ALfloat)>;
pub type LPALGETLISTENER3F =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               value1: *mut ALfloat,
                                               value2: *mut ALfloat,
                                               value3: *mut ALfloat)>;
pub type LPALGETLISTENERFV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               values: *mut ALfloat)>;
pub type LPALGETLISTENERI =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               value: *mut ALint)>;
pub type LPALGETLISTENER3I =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               value1: *mut ALint,
                                               value2: *mut ALint,
                                               value3: *mut ALint)>;
pub type LPALGETLISTENERIV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               values: *mut ALint)>;
pub type LPALGENSOURCES =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei,
                                               sources: *mut ALuint)>;
pub type LPALDELETESOURCES =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei,
                                               sources: *const ALuint)>;
pub type LPALISSOURCE =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint) -> ALboolean>;
pub type LPALSOURCEF =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum,
                                               value: ALfloat)>;
pub type LPALSOURCE3F =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum,
                                               value1: ALfloat,
                                               value2: ALfloat,
                                               value3: ALfloat)>;
pub type LPALSOURCEFV =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum,
                                               values: *const ALfloat)>;
pub type LPALSOURCEI =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum,
                                               value: ALint)>;
pub type LPALSOURCE3I =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum,
                                               value1: ALint, value2: ALint,
                                               value3: ALint)>;
pub type LPALSOURCEIV =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum,
                                               values: *const ALint)>;
pub type LPALGETSOURCEF =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum,
                                               value: *mut ALfloat)>;
pub type LPALGETSOURCE3F =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum,
                                               value1: *mut ALfloat,
                                               value2: *mut ALfloat,
                                               value3: *mut ALfloat)>;
pub type LPALGETSOURCEFV =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum,
                                               values: *mut ALfloat)>;
pub type LPALGETSOURCEI =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum,
                                               value: *mut ALint)>;
pub type LPALGETSOURCE3I =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum,
                                               value1: *mut ALint,
                                               value2: *mut ALint,
                                               value3: *mut ALint)>;
pub type LPALGETSOURCEIV =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum,
                                               values: *mut ALint)>;
pub type LPALSOURCEPLAYV =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei,
                                               sources: *const ALuint)>;
pub type LPALSOURCESTOPV =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei,
                                               sources: *const ALuint)>;
pub type LPALSOURCEREWINDV =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei,
                                               sources: *const ALuint)>;
pub type LPALSOURCEPAUSEV =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei,
                                               sources: *const ALuint)>;
pub type LPALSOURCEPLAY =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint)>;
pub type LPALSOURCESTOP =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint)>;
pub type LPALSOURCEREWIND =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint)>;
pub type LPALSOURCEPAUSE =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint)>;
pub type LPALSOURCEQUEUEBUFFERS =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, nb: ALsizei,
                                               buffers: *const ALuint)>;
pub type LPALSOURCEUNQUEUEBUFFERS =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, nb: ALsizei,
                                               buffers: *mut ALuint)>;
pub type LPALGENBUFFERS =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei,
                                               buffers: *mut ALuint)>;
pub type LPALDELETEBUFFERS =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei,
                                               buffers: *const ALuint)>;
pub type LPALISBUFFER =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint) -> ALboolean>;
pub type LPALBUFFERDATA =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, format: ALenum,
                                               data: *const ALvoid,
                                               size: ALsizei, freq: ALsizei)>;
pub type LPALBUFFERF =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum,
                                               value: ALfloat)>;
pub type LPALBUFFER3F =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum,
                                               value1: ALfloat,
                                               value2: ALfloat,
                                               value3: ALfloat)>;
pub type LPALBUFFERFV =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum,
                                               values: *const ALfloat)>;
pub type LPALBUFFERI =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum,
                                               value: ALint)>;
pub type LPALBUFFER3I =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum,
                                               value1: ALint, value2: ALint,
                                               value3: ALint)>;
pub type LPALBUFFERIV =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum,
                                               values: *const ALint)>;
pub type LPALGETBUFFERF =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum,
                                               value: *mut ALfloat)>;
pub type LPALGETBUFFER3F =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum,
                                               value1: *mut ALfloat,
                                               value2: *mut ALfloat,
                                               value3: *mut ALfloat)>;
pub type LPALGETBUFFERFV =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum,
                                               values: *mut ALfloat)>;
pub type LPALGETBUFFERI =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum,
                                               value: *mut ALint)>;
pub type LPALGETBUFFER3I =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum,
                                               value1: *mut ALint,
                                               value2: *mut ALint,
                                               value3: *mut ALint)>;
pub type LPALGETBUFFERIV =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum,
                                               values: *mut ALint)>;
pub type LPALDOPPLERFACTOR =
    ::std::option::Option<unsafe extern "C" fn(value: ALfloat)>;
pub type LPALDOPPLERVELOCITY =
    ::std::option::Option<unsafe extern "C" fn(value: ALfloat)>;
pub type LPALSPEEDOFSOUND =
    ::std::option::Option<unsafe extern "C" fn(value: ALfloat)>;
pub type LPALDISTANCEMODEL =
    ::std::option::Option<unsafe extern "C" fn(distanceModel: ALenum)>;
