/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
pub const __llvm__: ::std::os::raw::c_int = 1;
pub const __clang__: ::std::os::raw::c_int = 1;
pub const __clang_major__: ::std::os::raw::c_int = 3;
pub const __clang_minor__: ::std::os::raw::c_int = 8;
pub const __clang_patchlevel__: ::std::os::raw::c_int = 0;
pub const __GNUC_MINOR__: ::std::os::raw::c_int = 2;
pub const __GNUC_PATCHLEVEL__: ::std::os::raw::c_int = 1;
pub const __GNUC__: ::std::os::raw::c_int = 4;
pub const __GXX_ABI_VERSION: ::std::os::raw::c_int = 1002;
pub const __ATOMIC_RELAXED: ::std::os::raw::c_int = 0;
pub const __ATOMIC_CONSUME: ::std::os::raw::c_int = 1;
pub const __ATOMIC_ACQUIRE: ::std::os::raw::c_int = 2;
pub const __ATOMIC_RELEASE: ::std::os::raw::c_int = 3;
pub const __ATOMIC_ACQ_REL: ::std::os::raw::c_int = 4;
pub const __ATOMIC_SEQ_CST: ::std::os::raw::c_int = 5;
pub const __PRAGMA_REDEFINE_EXTNAME: ::std::os::raw::c_int = 1;
pub const __CONSTANT_CFSTRINGS__: ::std::os::raw::c_int = 1;
pub const __GXX_RTTI: ::std::os::raw::c_int = 1;
pub const __ORDER_LITTLE_ENDIAN__: ::std::os::raw::c_int = 1234;
pub const __ORDER_BIG_ENDIAN__: ::std::os::raw::c_int = 4321;
pub const __ORDER_PDP_ENDIAN__: ::std::os::raw::c_int = 3412;
pub const __BYTE_ORDER__: ::std::os::raw::c_int = 1234;
pub const __LITTLE_ENDIAN__: ::std::os::raw::c_int = 1;
pub const _LP64: ::std::os::raw::c_int = 1;
pub const __LP64__: ::std::os::raw::c_int = 1;
pub const __CHAR_BIT__: ::std::os::raw::c_int = 8;
pub const __SCHAR_MAX__: ::std::os::raw::c_int = 127;
pub const __SHRT_MAX__: ::std::os::raw::c_int = 32767;
pub const __INT_MAX__: ::std::os::raw::c_int = 2147483647;
pub const __LONG_MAX__: ::std::os::raw::c_int = 9223372036854775807;
pub const __LONG_LONG_MAX__: ::std::os::raw::c_int = 9223372036854775807;
pub const __WCHAR_MAX__: ::std::os::raw::c_int = 2147483647;
pub const __INTMAX_MAX__: ::std::os::raw::c_int = 9223372036854775807;
pub const __SIZE_MAX__: ::std::os::raw::c_int = -1;
pub const __UINTMAX_MAX__: ::std::os::raw::c_int = -1;
pub const __PTRDIFF_MAX__: ::std::os::raw::c_int = 9223372036854775807;
pub const __INTPTR_MAX__: ::std::os::raw::c_int = 9223372036854775807;
pub const __UINTPTR_MAX__: ::std::os::raw::c_int = -1;
pub const __SIZEOF_DOUBLE__: ::std::os::raw::c_int = 8;
pub const __SIZEOF_FLOAT__: ::std::os::raw::c_int = 4;
pub const __SIZEOF_INT__: ::std::os::raw::c_int = 4;
pub const __SIZEOF_LONG__: ::std::os::raw::c_int = 8;
pub const __SIZEOF_LONG_DOUBLE__: ::std::os::raw::c_int = 16;
pub const __SIZEOF_LONG_LONG__: ::std::os::raw::c_int = 8;
pub const __SIZEOF_POINTER__: ::std::os::raw::c_int = 8;
pub const __SIZEOF_SHORT__: ::std::os::raw::c_int = 2;
pub const __SIZEOF_PTRDIFF_T__: ::std::os::raw::c_int = 8;
pub const __SIZEOF_SIZE_T__: ::std::os::raw::c_int = 8;
pub const __SIZEOF_WCHAR_T__: ::std::os::raw::c_int = 4;
pub const __SIZEOF_WINT_T__: ::std::os::raw::c_int = 4;
pub const __SIZEOF_INT128__: ::std::os::raw::c_int = 16;
pub const __INTMAX_WIDTH__: ::std::os::raw::c_int = 64;
pub const __PTRDIFF_WIDTH__: ::std::os::raw::c_int = 64;
pub const __INTPTR_WIDTH__: ::std::os::raw::c_int = 64;
pub const __SIZE_WIDTH__: ::std::os::raw::c_int = 64;
pub const __WCHAR_WIDTH__: ::std::os::raw::c_int = 32;
pub const __WINT_WIDTH__: ::std::os::raw::c_int = 32;
pub const __SIG_ATOMIC_WIDTH__: ::std::os::raw::c_int = 32;
pub const __SIG_ATOMIC_MAX__: ::std::os::raw::c_int = 2147483647;
pub const __UINTMAX_WIDTH__: ::std::os::raw::c_int = 64;
pub const __UINTPTR_WIDTH__: ::std::os::raw::c_int = 64;
pub const __FLT_HAS_DENORM__: ::std::os::raw::c_int = 1;
pub const __FLT_DIG__: ::std::os::raw::c_int = 6;
pub const __FLT_DECIMAL_DIG__: ::std::os::raw::c_int = 9;
pub const __FLT_HAS_INFINITY__: ::std::os::raw::c_int = 1;
pub const __FLT_HAS_QUIET_NAN__: ::std::os::raw::c_int = 1;
pub const __FLT_MANT_DIG__: ::std::os::raw::c_int = 24;
pub const __FLT_MAX_10_EXP__: ::std::os::raw::c_int = 38;
pub const __FLT_MAX_EXP__: ::std::os::raw::c_int = 128;
pub const __FLT_MIN_10_EXP__: ::std::os::raw::c_int = -37;
pub const __FLT_MIN_EXP__: ::std::os::raw::c_int = -125;
pub const __DBL_HAS_DENORM__: ::std::os::raw::c_int = 1;
pub const __DBL_DIG__: ::std::os::raw::c_int = 15;
pub const __DBL_DECIMAL_DIG__: ::std::os::raw::c_int = 17;
pub const __DBL_HAS_INFINITY__: ::std::os::raw::c_int = 1;
pub const __DBL_HAS_QUIET_NAN__: ::std::os::raw::c_int = 1;
pub const __DBL_MANT_DIG__: ::std::os::raw::c_int = 53;
pub const __DBL_MAX_10_EXP__: ::std::os::raw::c_int = 308;
pub const __DBL_MAX_EXP__: ::std::os::raw::c_int = 1024;
pub const __DBL_MIN_10_EXP__: ::std::os::raw::c_int = -307;
pub const __DBL_MIN_EXP__: ::std::os::raw::c_int = -1021;
pub const __LDBL_HAS_DENORM__: ::std::os::raw::c_int = 1;
pub const __LDBL_DIG__: ::std::os::raw::c_int = 18;
pub const __LDBL_DECIMAL_DIG__: ::std::os::raw::c_int = 21;
pub const __LDBL_HAS_INFINITY__: ::std::os::raw::c_int = 1;
pub const __LDBL_HAS_QUIET_NAN__: ::std::os::raw::c_int = 1;
pub const __LDBL_MANT_DIG__: ::std::os::raw::c_int = 64;
pub const __LDBL_MAX_10_EXP__: ::std::os::raw::c_int = 4932;
pub const __LDBL_MAX_EXP__: ::std::os::raw::c_int = 16384;
pub const __LDBL_MIN_10_EXP__: ::std::os::raw::c_int = -4931;
pub const __LDBL_MIN_EXP__: ::std::os::raw::c_int = -16381;
pub const __POINTER_WIDTH__: ::std::os::raw::c_int = 64;
pub const __BIGGEST_ALIGNMENT__: ::std::os::raw::c_int = 16;
pub const __WINT_UNSIGNED__: ::std::os::raw::c_int = 1;
pub const __UINT8_MAX__: ::std::os::raw::c_int = 255;
pub const __INT8_MAX__: ::std::os::raw::c_int = 127;
pub const __UINT16_MAX__: ::std::os::raw::c_int = 65535;
pub const __INT16_MAX__: ::std::os::raw::c_int = 32767;
pub const __UINT32_MAX__: ::std::os::raw::c_int = 4294967295;
pub const __INT32_MAX__: ::std::os::raw::c_int = 2147483647;
pub const __UINT64_MAX__: ::std::os::raw::c_int = -1;
pub const __INT64_MAX__: ::std::os::raw::c_int = 9223372036854775807;
pub const __INT_LEAST8_MAX__: ::std::os::raw::c_int = 127;
pub const __UINT_LEAST8_MAX__: ::std::os::raw::c_int = 255;
pub const __INT_LEAST16_MAX__: ::std::os::raw::c_int = 32767;
pub const __UINT_LEAST16_MAX__: ::std::os::raw::c_int = 65535;
pub const __INT_LEAST32_MAX__: ::std::os::raw::c_int = 2147483647;
pub const __UINT_LEAST32_MAX__: ::std::os::raw::c_int = 4294967295;
pub const __INT_LEAST64_MAX__: ::std::os::raw::c_int = 9223372036854775807;
pub const __UINT_LEAST64_MAX__: ::std::os::raw::c_int = -1;
pub const __INT_FAST8_MAX__: ::std::os::raw::c_int = 127;
pub const __UINT_FAST8_MAX__: ::std::os::raw::c_int = 255;
pub const __INT_FAST16_MAX__: ::std::os::raw::c_int = 32767;
pub const __UINT_FAST16_MAX__: ::std::os::raw::c_int = 65535;
pub const __INT_FAST32_MAX__: ::std::os::raw::c_int = 2147483647;
pub const __UINT_FAST32_MAX__: ::std::os::raw::c_int = 4294967295;
pub const __INT_FAST64_MAX__: ::std::os::raw::c_int = 9223372036854775807;
pub const __UINT_FAST64_MAX__: ::std::os::raw::c_int = -1;
pub const __FINITE_MATH_ONLY__: ::std::os::raw::c_int = 0;
pub const __GNUC_STDC_INLINE__: ::std::os::raw::c_int = 1;
pub const __GCC_ATOMIC_TEST_AND_SET_TRUEVAL: ::std::os::raw::c_int = 1;
pub const __GCC_ATOMIC_BOOL_LOCK_FREE: ::std::os::raw::c_int = 2;
pub const __GCC_ATOMIC_CHAR_LOCK_FREE: ::std::os::raw::c_int = 2;
pub const __GCC_ATOMIC_CHAR16_T_LOCK_FREE: ::std::os::raw::c_int = 2;
pub const __GCC_ATOMIC_CHAR32_T_LOCK_FREE: ::std::os::raw::c_int = 2;
pub const __GCC_ATOMIC_WCHAR_T_LOCK_FREE: ::std::os::raw::c_int = 2;
pub const __GCC_ATOMIC_SHORT_LOCK_FREE: ::std::os::raw::c_int = 2;
pub const __GCC_ATOMIC_INT_LOCK_FREE: ::std::os::raw::c_int = 2;
pub const __GCC_ATOMIC_LONG_LOCK_FREE: ::std::os::raw::c_int = 2;
pub const __GCC_ATOMIC_LLONG_LOCK_FREE: ::std::os::raw::c_int = 2;
pub const __GCC_ATOMIC_POINTER_LOCK_FREE: ::std::os::raw::c_int = 2;
pub const __NO_INLINE__: ::std::os::raw::c_int = 1;
pub const __FLT_EVAL_METHOD__: ::std::os::raw::c_int = 0;
pub const __FLT_RADIX__: ::std::os::raw::c_int = 2;
pub const __DECIMAL_DIG__: ::std::os::raw::c_int = 21;
pub const __amd64__: ::std::os::raw::c_int = 1;
pub const __amd64: ::std::os::raw::c_int = 1;
pub const __x86_64: ::std::os::raw::c_int = 1;
pub const __x86_64__: ::std::os::raw::c_int = 1;
pub const __k8: ::std::os::raw::c_int = 1;
pub const __k8__: ::std::os::raw::c_int = 1;
pub const __tune_k8__: ::std::os::raw::c_int = 1;
pub const __NO_MATH_INLINES: ::std::os::raw::c_int = 1;
pub const __FXSR__: ::std::os::raw::c_int = 1;
pub const __SSE2__: ::std::os::raw::c_int = 1;
pub const __SSE2_MATH__: ::std::os::raw::c_int = 1;
pub const __SSE__: ::std::os::raw::c_int = 1;
pub const __SSE_MATH__: ::std::os::raw::c_int = 1;
pub const __MMX__: ::std::os::raw::c_int = 1;
pub const __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1: ::std::os::raw::c_int = 1;
pub const __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2: ::std::os::raw::c_int = 1;
pub const __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4: ::std::os::raw::c_int = 1;
pub const __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8: ::std::os::raw::c_int = 1;
pub const unix: ::std::os::raw::c_int = 1;
pub const __unix: ::std::os::raw::c_int = 1;
pub const __unix__: ::std::os::raw::c_int = 1;
pub const linux: ::std::os::raw::c_int = 1;
pub const __linux: ::std::os::raw::c_int = 1;
pub const __linux__: ::std::os::raw::c_int = 1;
pub const __gnu_linux__: ::std::os::raw::c_int = 1;
pub const __ELF__: ::std::os::raw::c_int = 1;
pub const __STDC__: ::std::os::raw::c_int = 1;
pub const __STDC_HOSTED__: ::std::os::raw::c_int = 1;
pub const __STDC_VERSION__: ::std::os::raw::c_int = 201112;
pub const __STDC_UTF_16__: ::std::os::raw::c_int = 1;
pub const __STDC_UTF_32__: ::std::os::raw::c_int = 1;
pub const __ANDROID__: ::std::os::raw::c_int = 1;
pub const __KERNEL_STRICT_NAMES: ::std::os::raw::c_int = 1;
pub const INT8_MIN: ::std::os::raw::c_int = -128;
pub const INT8_MAX: ::std::os::raw::c_int = 127;
pub const INT_LEAST8_MIN: ::std::os::raw::c_int = -128;
pub const INT_LEAST8_MAX: ::std::os::raw::c_int = 127;
pub const INT_FAST8_MIN: ::std::os::raw::c_int = -128;
pub const INT_FAST8_MAX: ::std::os::raw::c_int = 127;
pub const UINT8_MAX: ::std::os::raw::c_int = 255;
pub const UINT_LEAST8_MAX: ::std::os::raw::c_int = 255;
pub const UINT_FAST8_MAX: ::std::os::raw::c_int = 255;
pub const INT16_MIN: ::std::os::raw::c_int = -32768;
pub const INT16_MAX: ::std::os::raw::c_int = 32767;
pub const INT_LEAST16_MIN: ::std::os::raw::c_int = -32768;
pub const INT_LEAST16_MAX: ::std::os::raw::c_int = 32767;
pub const UINT16_MAX: ::std::os::raw::c_int = 65535;
pub const UINT_LEAST16_MAX: ::std::os::raw::c_int = 65535;
pub const INT32_MIN: ::std::os::raw::c_int = -2147483648;
pub const INT32_MAX: ::std::os::raw::c_int = 2147483647;
pub const INT_LEAST32_MIN: ::std::os::raw::c_int = -2147483648;
pub const INT_LEAST32_MAX: ::std::os::raw::c_int = 2147483647;
pub const INT_FAST32_MIN: ::std::os::raw::c_int = -2147483648;
pub const INT_FAST32_MAX: ::std::os::raw::c_int = 2147483647;
pub const UINT32_MAX: ::std::os::raw::c_int = 4294967295;
pub const UINT_LEAST32_MAX: ::std::os::raw::c_int = 4294967295;
pub const UINT_FAST32_MAX: ::std::os::raw::c_int = 4294967295;
pub const INTPTR_MIN: ::std::os::raw::c_int = -2147483648;
pub const INTPTR_MAX: ::std::os::raw::c_int = 2147483647;
pub const UINTPTR_MAX: ::std::os::raw::c_int = 4294967295;
pub const PTRDIFF_MIN: ::std::os::raw::c_int = -2147483648;
pub const PTRDIFF_MAX: ::std::os::raw::c_int = 2147483647;
pub const SIG_ATOMIC_MIN: ::std::os::raw::c_int = -2147483648;
pub const SIG_ATOMIC_MAX: ::std::os::raw::c_int = 2147483647;
pub const __ANDROID_API__: ::std::os::raw::c_int = 19;
pub const WCHAR_MAX: ::std::os::raw::c_int = 2147483647;
pub const WCHAR_MIN: ::std::os::raw::c_int = -2147483648;
pub const WINT_MIN: ::std::os::raw::c_int = -2147483648;
pub const WINT_MAX: ::std::os::raw::c_int = 2147483647;
pub const _BITSIZE: ::std::os::raw::c_int = 32;
pub const __POSIX_VISIBLE: ::std::os::raw::c_int = 200809;
pub const __XSI_VISIBLE: ::std::os::raw::c_int = 700;
pub const __BSD_VISIBLE: ::std::os::raw::c_int = 1;
pub const __ISO_C_VISIBLE: ::std::os::raw::c_int = 1999;
pub const __XPG_VISIBLE: ::std::os::raw::c_int = 700;
pub const __BIONIC__: ::std::os::raw::c_int = 1;
pub const __WORDSIZE: ::std::os::raw::c_int = 64;
pub const ALC_INVALID: ::std::os::raw::c_int = 0;
pub const ALC_VERSION_0_1: ::std::os::raw::c_int = 1;
pub const ALC_FALSE: ::std::os::raw::c_int = 0;
pub const ALC_TRUE: ::std::os::raw::c_int = 1;
pub const ALC_FREQUENCY: ::std::os::raw::c_int = 4103;
pub const ALC_REFRESH: ::std::os::raw::c_int = 4104;
pub const ALC_SYNC: ::std::os::raw::c_int = 4105;
pub const ALC_MONO_SOURCES: ::std::os::raw::c_int = 4112;
pub const ALC_STEREO_SOURCES: ::std::os::raw::c_int = 4113;
pub const ALC_NO_ERROR: ::std::os::raw::c_int = 0;
pub const ALC_INVALID_DEVICE: ::std::os::raw::c_int = 40961;
pub const ALC_INVALID_CONTEXT: ::std::os::raw::c_int = 40962;
pub const ALC_INVALID_ENUM: ::std::os::raw::c_int = 40963;
pub const ALC_INVALID_VALUE: ::std::os::raw::c_int = 40964;
pub const ALC_OUT_OF_MEMORY: ::std::os::raw::c_int = 40965;
pub const ALC_MAJOR_VERSION: ::std::os::raw::c_int = 4096;
pub const ALC_MINOR_VERSION: ::std::os::raw::c_int = 4097;
pub const ALC_ATTRIBUTES_SIZE: ::std::os::raw::c_int = 4098;
pub const ALC_ALL_ATTRIBUTES: ::std::os::raw::c_int = 4099;
pub const ALC_DEFAULT_DEVICE_SPECIFIER: ::std::os::raw::c_int = 4100;
pub const ALC_DEVICE_SPECIFIER: ::std::os::raw::c_int = 4101;
pub const ALC_EXTENSIONS: ::std::os::raw::c_int = 4102;
pub const ALC_EXT_CAPTURE: ::std::os::raw::c_int = 1;
pub const ALC_CAPTURE_DEVICE_SPECIFIER: ::std::os::raw::c_int = 784;
pub const ALC_CAPTURE_DEFAULT_DEVICE_SPECIFIER: ::std::os::raw::c_int = 785;
pub const ALC_CAPTURE_SAMPLES: ::std::os::raw::c_int = 786;
pub const ALC_ENUMERATE_ALL_EXT: ::std::os::raw::c_int = 1;
pub const ALC_DEFAULT_ALL_DEVICES_SPECIFIER: ::std::os::raw::c_int = 4114;
pub const ALC_ALL_DEVICES_SPECIFIER: ::std::os::raw::c_int = 4115;
pub const AL_INVALID: ::std::os::raw::c_int = -1;
pub const AL_NONE: ::std::os::raw::c_int = 0;
pub const AL_FALSE: ::std::os::raw::c_int = 0;
pub const AL_TRUE: ::std::os::raw::c_int = 1;
pub const AL_SOURCE_RELATIVE: ::std::os::raw::c_int = 514;
pub const AL_CONE_INNER_ANGLE: ::std::os::raw::c_int = 4097;
pub const AL_CONE_OUTER_ANGLE: ::std::os::raw::c_int = 4098;
pub const AL_PITCH: ::std::os::raw::c_int = 4099;
pub const AL_POSITION: ::std::os::raw::c_int = 4100;
pub const AL_DIRECTION: ::std::os::raw::c_int = 4101;
pub const AL_VELOCITY: ::std::os::raw::c_int = 4102;
pub const AL_LOOPING: ::std::os::raw::c_int = 4103;
pub const AL_BUFFER: ::std::os::raw::c_int = 4105;
pub const AL_GAIN: ::std::os::raw::c_int = 4106;
pub const AL_MIN_GAIN: ::std::os::raw::c_int = 4109;
pub const AL_MAX_GAIN: ::std::os::raw::c_int = 4110;
pub const AL_ORIENTATION: ::std::os::raw::c_int = 4111;
pub const AL_SOURCE_STATE: ::std::os::raw::c_int = 4112;
pub const AL_INITIAL: ::std::os::raw::c_int = 4113;
pub const AL_PLAYING: ::std::os::raw::c_int = 4114;
pub const AL_PAUSED: ::std::os::raw::c_int = 4115;
pub const AL_STOPPED: ::std::os::raw::c_int = 4116;
pub const AL_BUFFERS_QUEUED: ::std::os::raw::c_int = 4117;
pub const AL_BUFFERS_PROCESSED: ::std::os::raw::c_int = 4118;
pub const AL_REFERENCE_DISTANCE: ::std::os::raw::c_int = 4128;
pub const AL_ROLLOFF_FACTOR: ::std::os::raw::c_int = 4129;
pub const AL_CONE_OUTER_GAIN: ::std::os::raw::c_int = 4130;
pub const AL_MAX_DISTANCE: ::std::os::raw::c_int = 4131;
pub const AL_SEC_OFFSET: ::std::os::raw::c_int = 4132;
pub const AL_SAMPLE_OFFSET: ::std::os::raw::c_int = 4133;
pub const AL_BYTE_OFFSET: ::std::os::raw::c_int = 4134;
pub const AL_SOURCE_TYPE: ::std::os::raw::c_int = 4135;
pub const AL_STATIC: ::std::os::raw::c_int = 4136;
pub const AL_STREAMING: ::std::os::raw::c_int = 4137;
pub const AL_UNDETERMINED: ::std::os::raw::c_int = 4144;
pub const AL_FORMAT_MONO8: ::std::os::raw::c_int = 4352;
pub const AL_FORMAT_MONO16: ::std::os::raw::c_int = 4353;
pub const AL_FORMAT_STEREO8: ::std::os::raw::c_int = 4354;
pub const AL_FORMAT_STEREO16: ::std::os::raw::c_int = 4355;
pub const AL_FREQUENCY: ::std::os::raw::c_int = 8193;
pub const AL_BITS: ::std::os::raw::c_int = 8194;
pub const AL_CHANNELS: ::std::os::raw::c_int = 8195;
pub const AL_SIZE: ::std::os::raw::c_int = 8196;
pub const AL_UNUSED: ::std::os::raw::c_int = 8208;
pub const AL_PENDING: ::std::os::raw::c_int = 8209;
pub const AL_PROCESSED: ::std::os::raw::c_int = 8210;
pub const AL_NO_ERROR: ::std::os::raw::c_int = 0;
pub const AL_INVALID_NAME: ::std::os::raw::c_int = 40961;
pub const AL_INVALID_ENUM: ::std::os::raw::c_int = 40962;
pub const AL_INVALID_VALUE: ::std::os::raw::c_int = 40963;
pub const AL_INVALID_OPERATION: ::std::os::raw::c_int = 40964;
pub const AL_OUT_OF_MEMORY: ::std::os::raw::c_int = 40965;
pub const AL_VENDOR: ::std::os::raw::c_int = 45057;
pub const AL_VERSION: ::std::os::raw::c_int = 45058;
pub const AL_RENDERER: ::std::os::raw::c_int = 45059;
pub const AL_EXTENSIONS: ::std::os::raw::c_int = 45060;
pub const AL_DOPPLER_FACTOR: ::std::os::raw::c_int = 49152;
pub const AL_DOPPLER_VELOCITY: ::std::os::raw::c_int = 49153;
pub const AL_SPEED_OF_SOUND: ::std::os::raw::c_int = 49155;
pub const AL_DISTANCE_MODEL: ::std::os::raw::c_int = 53248;
pub const AL_INVERSE_DISTANCE: ::std::os::raw::c_int = 53249;
pub const AL_INVERSE_DISTANCE_CLAMPED: ::std::os::raw::c_int = 53250;
pub const AL_LINEAR_DISTANCE: ::std::os::raw::c_int = 53251;
pub const AL_LINEAR_DISTANCE_CLAMPED: ::std::os::raw::c_int = 53252;
pub const AL_EXPONENT_DISTANCE: ::std::os::raw::c_int = 53253;
pub const AL_EXPONENT_DISTANCE_CLAMPED: ::std::os::raw::c_int = 53254;
pub const AL_LOKI_IMA_ADPCM_format: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_IMA_ADPCM_MONO16_EXT: ::std::os::raw::c_int = 65536;
pub const AL_FORMAT_IMA_ADPCM_STEREO16_EXT: ::std::os::raw::c_int = 65537;
pub const AL_LOKI_WAVE_format: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_WAVE_EXT: ::std::os::raw::c_int = 65538;
pub const AL_EXT_vorbis: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_VORBIS_EXT: ::std::os::raw::c_int = 65539;
pub const AL_LOKI_quadriphonic: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_QUAD8_LOKI: ::std::os::raw::c_int = 65540;
pub const AL_FORMAT_QUAD16_LOKI: ::std::os::raw::c_int = 65541;
pub const AL_EXT_float32: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_MONO_FLOAT32: ::std::os::raw::c_int = 65552;
pub const AL_FORMAT_STEREO_FLOAT32: ::std::os::raw::c_int = 65553;
pub const AL_EXT_double: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_MONO_DOUBLE_EXT: ::std::os::raw::c_int = 65554;
pub const AL_FORMAT_STEREO_DOUBLE_EXT: ::std::os::raw::c_int = 65555;
pub const AL_EXT_MULAW: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_MONO_MULAW_EXT: ::std::os::raw::c_int = 65556;
pub const AL_FORMAT_STEREO_MULAW_EXT: ::std::os::raw::c_int = 65557;
pub const AL_EXT_ALAW: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_MONO_ALAW_EXT: ::std::os::raw::c_int = 65558;
pub const AL_FORMAT_STEREO_ALAW_EXT: ::std::os::raw::c_int = 65559;
pub const ALC_LOKI_audio_channel: ::std::os::raw::c_int = 1;
pub const ALC_CHAN_MAIN_LOKI: ::std::os::raw::c_int = 5242881;
pub const ALC_CHAN_PCM_LOKI: ::std::os::raw::c_int = 5242882;
pub const ALC_CHAN_CD_LOKI: ::std::os::raw::c_int = 5242883;
pub const AL_EXT_MCFORMATS: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_QUAD8: ::std::os::raw::c_int = 4612;
pub const AL_FORMAT_QUAD16: ::std::os::raw::c_int = 4613;
pub const AL_FORMAT_QUAD32: ::std::os::raw::c_int = 4614;
pub const AL_FORMAT_REAR8: ::std::os::raw::c_int = 4615;
pub const AL_FORMAT_REAR16: ::std::os::raw::c_int = 4616;
pub const AL_FORMAT_REAR32: ::std::os::raw::c_int = 4617;
pub const AL_FORMAT_51CHN8: ::std::os::raw::c_int = 4618;
pub const AL_FORMAT_51CHN16: ::std::os::raw::c_int = 4619;
pub const AL_FORMAT_51CHN32: ::std::os::raw::c_int = 4620;
pub const AL_FORMAT_61CHN8: ::std::os::raw::c_int = 4621;
pub const AL_FORMAT_61CHN16: ::std::os::raw::c_int = 4622;
pub const AL_FORMAT_61CHN32: ::std::os::raw::c_int = 4623;
pub const AL_FORMAT_71CHN8: ::std::os::raw::c_int = 4624;
pub const AL_FORMAT_71CHN16: ::std::os::raw::c_int = 4625;
pub const AL_FORMAT_71CHN32: ::std::os::raw::c_int = 4626;
pub const AL_EXT_MULAW_MCFORMATS: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_MONO_MULAW: ::std::os::raw::c_int = 65556;
pub const AL_FORMAT_STEREO_MULAW: ::std::os::raw::c_int = 65557;
pub const AL_FORMAT_QUAD_MULAW: ::std::os::raw::c_int = 65569;
pub const AL_FORMAT_REAR_MULAW: ::std::os::raw::c_int = 65570;
pub const AL_FORMAT_51CHN_MULAW: ::std::os::raw::c_int = 65571;
pub const AL_FORMAT_61CHN_MULAW: ::std::os::raw::c_int = 65572;
pub const AL_FORMAT_71CHN_MULAW: ::std::os::raw::c_int = 65573;
pub const AL_EXT_IMA4: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_MONO_IMA4: ::std::os::raw::c_int = 4864;
pub const AL_FORMAT_STEREO_IMA4: ::std::os::raw::c_int = 4865;
pub const AL_EXT_STATIC_BUFFER: ::std::os::raw::c_int = 1;
pub const ALC_EXT_EFX: ::std::os::raw::c_int = 1;
pub const ALC_EFX_MAJOR_VERSION: ::std::os::raw::c_int = 131073;
pub const ALC_EFX_MINOR_VERSION: ::std::os::raw::c_int = 131074;
pub const ALC_MAX_AUXILIARY_SENDS: ::std::os::raw::c_int = 131075;
pub const AL_METERS_PER_UNIT: ::std::os::raw::c_int = 131076;
pub const AL_DIRECT_FILTER: ::std::os::raw::c_int = 131077;
pub const AL_AUXILIARY_SEND_FILTER: ::std::os::raw::c_int = 131078;
pub const AL_AIR_ABSORPTION_FACTOR: ::std::os::raw::c_int = 131079;
pub const AL_ROOM_ROLLOFF_FACTOR: ::std::os::raw::c_int = 131080;
pub const AL_CONE_OUTER_GAINHF: ::std::os::raw::c_int = 131081;
pub const AL_DIRECT_FILTER_GAINHF_AUTO: ::std::os::raw::c_int = 131082;
pub const AL_AUXILIARY_SEND_FILTER_GAIN_AUTO: ::std::os::raw::c_int = 131083;
pub const AL_AUXILIARY_SEND_FILTER_GAINHF_AUTO: ::std::os::raw::c_int =
    131084;
pub const AL_REVERB_DENSITY: ::std::os::raw::c_int = 1;
pub const AL_REVERB_DIFFUSION: ::std::os::raw::c_int = 2;
pub const AL_REVERB_GAIN: ::std::os::raw::c_int = 3;
pub const AL_REVERB_GAINHF: ::std::os::raw::c_int = 4;
pub const AL_REVERB_DECAY_TIME: ::std::os::raw::c_int = 5;
pub const AL_REVERB_DECAY_HFRATIO: ::std::os::raw::c_int = 6;
pub const AL_REVERB_REFLECTIONS_GAIN: ::std::os::raw::c_int = 7;
pub const AL_REVERB_REFLECTIONS_DELAY: ::std::os::raw::c_int = 8;
pub const AL_REVERB_LATE_REVERB_GAIN: ::std::os::raw::c_int = 9;
pub const AL_REVERB_LATE_REVERB_DELAY: ::std::os::raw::c_int = 10;
pub const AL_REVERB_AIR_ABSORPTION_GAINHF: ::std::os::raw::c_int = 11;
pub const AL_REVERB_ROOM_ROLLOFF_FACTOR: ::std::os::raw::c_int = 12;
pub const AL_REVERB_DECAY_HFLIMIT: ::std::os::raw::c_int = 13;
pub const AL_EAXREVERB_DENSITY: ::std::os::raw::c_int = 1;
pub const AL_EAXREVERB_DIFFUSION: ::std::os::raw::c_int = 2;
pub const AL_EAXREVERB_GAIN: ::std::os::raw::c_int = 3;
pub const AL_EAXREVERB_GAINHF: ::std::os::raw::c_int = 4;
pub const AL_EAXREVERB_GAINLF: ::std::os::raw::c_int = 5;
pub const AL_EAXREVERB_DECAY_TIME: ::std::os::raw::c_int = 6;
pub const AL_EAXREVERB_DECAY_HFRATIO: ::std::os::raw::c_int = 7;
pub const AL_EAXREVERB_DECAY_LFRATIO: ::std::os::raw::c_int = 8;
pub const AL_EAXREVERB_REFLECTIONS_GAIN: ::std::os::raw::c_int = 9;
pub const AL_EAXREVERB_REFLECTIONS_DELAY: ::std::os::raw::c_int = 10;
pub const AL_EAXREVERB_REFLECTIONS_PAN: ::std::os::raw::c_int = 11;
pub const AL_EAXREVERB_LATE_REVERB_GAIN: ::std::os::raw::c_int = 12;
pub const AL_EAXREVERB_LATE_REVERB_DELAY: ::std::os::raw::c_int = 13;
pub const AL_EAXREVERB_LATE_REVERB_PAN: ::std::os::raw::c_int = 14;
pub const AL_EAXREVERB_ECHO_TIME: ::std::os::raw::c_int = 15;
pub const AL_EAXREVERB_ECHO_DEPTH: ::std::os::raw::c_int = 16;
pub const AL_EAXREVERB_MODULATION_TIME: ::std::os::raw::c_int = 17;
pub const AL_EAXREVERB_MODULATION_DEPTH: ::std::os::raw::c_int = 18;
pub const AL_EAXREVERB_AIR_ABSORPTION_GAINHF: ::std::os::raw::c_int = 19;
pub const AL_EAXREVERB_HFREFERENCE: ::std::os::raw::c_int = 20;
pub const AL_EAXREVERB_LFREFERENCE: ::std::os::raw::c_int = 21;
pub const AL_EAXREVERB_ROOM_ROLLOFF_FACTOR: ::std::os::raw::c_int = 22;
pub const AL_EAXREVERB_DECAY_HFLIMIT: ::std::os::raw::c_int = 23;
pub const AL_CHORUS_WAVEFORM: ::std::os::raw::c_int = 1;
pub const AL_CHORUS_PHASE: ::std::os::raw::c_int = 2;
pub const AL_CHORUS_RATE: ::std::os::raw::c_int = 3;
pub const AL_CHORUS_DEPTH: ::std::os::raw::c_int = 4;
pub const AL_CHORUS_FEEDBACK: ::std::os::raw::c_int = 5;
pub const AL_CHORUS_DELAY: ::std::os::raw::c_int = 6;
pub const AL_DISTORTION_EDGE: ::std::os::raw::c_int = 1;
pub const AL_DISTORTION_GAIN: ::std::os::raw::c_int = 2;
pub const AL_DISTORTION_LOWPASS_CUTOFF: ::std::os::raw::c_int = 3;
pub const AL_DISTORTION_EQCENTER: ::std::os::raw::c_int = 4;
pub const AL_DISTORTION_EQBANDWIDTH: ::std::os::raw::c_int = 5;
pub const AL_ECHO_DELAY: ::std::os::raw::c_int = 1;
pub const AL_ECHO_LRDELAY: ::std::os::raw::c_int = 2;
pub const AL_ECHO_DAMPING: ::std::os::raw::c_int = 3;
pub const AL_ECHO_FEEDBACK: ::std::os::raw::c_int = 4;
pub const AL_ECHO_SPREAD: ::std::os::raw::c_int = 5;
pub const AL_FLANGER_WAVEFORM: ::std::os::raw::c_int = 1;
pub const AL_FLANGER_PHASE: ::std::os::raw::c_int = 2;
pub const AL_FLANGER_RATE: ::std::os::raw::c_int = 3;
pub const AL_FLANGER_DEPTH: ::std::os::raw::c_int = 4;
pub const AL_FLANGER_FEEDBACK: ::std::os::raw::c_int = 5;
pub const AL_FLANGER_DELAY: ::std::os::raw::c_int = 6;
pub const AL_FREQUENCY_SHIFTER_FREQUENCY: ::std::os::raw::c_int = 1;
pub const AL_FREQUENCY_SHIFTER_LEFT_DIRECTION: ::std::os::raw::c_int = 2;
pub const AL_FREQUENCY_SHIFTER_RIGHT_DIRECTION: ::std::os::raw::c_int = 3;
pub const AL_VOCAL_MORPHER_PHONEMEA: ::std::os::raw::c_int = 1;
pub const AL_VOCAL_MORPHER_PHONEMEA_COARSE_TUNING: ::std::os::raw::c_int = 2;
pub const AL_VOCAL_MORPHER_PHONEMEB: ::std::os::raw::c_int = 3;
pub const AL_VOCAL_MORPHER_PHONEMEB_COARSE_TUNING: ::std::os::raw::c_int = 4;
pub const AL_VOCAL_MORPHER_WAVEFORM: ::std::os::raw::c_int = 5;
pub const AL_VOCAL_MORPHER_RATE: ::std::os::raw::c_int = 6;
pub const AL_PITCH_SHIFTER_COARSE_TUNE: ::std::os::raw::c_int = 1;
pub const AL_PITCH_SHIFTER_FINE_TUNE: ::std::os::raw::c_int = 2;
pub const AL_RING_MODULATOR_FREQUENCY: ::std::os::raw::c_int = 1;
pub const AL_RING_MODULATOR_HIGHPASS_CUTOFF: ::std::os::raw::c_int = 2;
pub const AL_RING_MODULATOR_WAVEFORM: ::std::os::raw::c_int = 3;
pub const AL_AUTOWAH_ATTACK_TIME: ::std::os::raw::c_int = 1;
pub const AL_AUTOWAH_RELEASE_TIME: ::std::os::raw::c_int = 2;
pub const AL_AUTOWAH_RESONANCE: ::std::os::raw::c_int = 3;
pub const AL_AUTOWAH_PEAK_GAIN: ::std::os::raw::c_int = 4;
pub const AL_COMPRESSOR_ONOFF: ::std::os::raw::c_int = 1;
pub const AL_EQUALIZER_LOW_GAIN: ::std::os::raw::c_int = 1;
pub const AL_EQUALIZER_LOW_CUTOFF: ::std::os::raw::c_int = 2;
pub const AL_EQUALIZER_MID1_GAIN: ::std::os::raw::c_int = 3;
pub const AL_EQUALIZER_MID1_CENTER: ::std::os::raw::c_int = 4;
pub const AL_EQUALIZER_MID1_WIDTH: ::std::os::raw::c_int = 5;
pub const AL_EQUALIZER_MID2_GAIN: ::std::os::raw::c_int = 6;
pub const AL_EQUALIZER_MID2_CENTER: ::std::os::raw::c_int = 7;
pub const AL_EQUALIZER_MID2_WIDTH: ::std::os::raw::c_int = 8;
pub const AL_EQUALIZER_HIGH_GAIN: ::std::os::raw::c_int = 9;
pub const AL_EQUALIZER_HIGH_CUTOFF: ::std::os::raw::c_int = 10;
pub const AL_EFFECT_FIRST_PARAMETER: ::std::os::raw::c_int = 0;
pub const AL_EFFECT_LAST_PARAMETER: ::std::os::raw::c_int = 32768;
pub const AL_EFFECT_TYPE: ::std::os::raw::c_int = 32769;
pub const AL_EFFECT_NULL: ::std::os::raw::c_int = 0;
pub const AL_EFFECT_REVERB: ::std::os::raw::c_int = 1;
pub const AL_EFFECT_CHORUS: ::std::os::raw::c_int = 2;
pub const AL_EFFECT_DISTORTION: ::std::os::raw::c_int = 3;
pub const AL_EFFECT_ECHO: ::std::os::raw::c_int = 4;
pub const AL_EFFECT_FLANGER: ::std::os::raw::c_int = 5;
pub const AL_EFFECT_FREQUENCY_SHIFTER: ::std::os::raw::c_int = 6;
pub const AL_EFFECT_VOCAL_MORPHER: ::std::os::raw::c_int = 7;
pub const AL_EFFECT_PITCH_SHIFTER: ::std::os::raw::c_int = 8;
pub const AL_EFFECT_RING_MODULATOR: ::std::os::raw::c_int = 9;
pub const AL_EFFECT_AUTOWAH: ::std::os::raw::c_int = 10;
pub const AL_EFFECT_COMPRESSOR: ::std::os::raw::c_int = 11;
pub const AL_EFFECT_EQUALIZER: ::std::os::raw::c_int = 12;
pub const AL_EFFECT_EAXREVERB: ::std::os::raw::c_int = 32768;
pub const AL_EFFECTSLOT_EFFECT: ::std::os::raw::c_int = 1;
pub const AL_EFFECTSLOT_GAIN: ::std::os::raw::c_int = 2;
pub const AL_EFFECTSLOT_AUXILIARY_SEND_AUTO: ::std::os::raw::c_int = 3;
pub const AL_EFFECTSLOT_NULL: ::std::os::raw::c_int = 0;
pub const AL_LOWPASS_GAIN: ::std::os::raw::c_int = 1;
pub const AL_LOWPASS_GAINHF: ::std::os::raw::c_int = 2;
pub const AL_HIGHPASS_GAIN: ::std::os::raw::c_int = 1;
pub const AL_HIGHPASS_GAINLF: ::std::os::raw::c_int = 2;
pub const AL_BANDPASS_GAIN: ::std::os::raw::c_int = 1;
pub const AL_BANDPASS_GAINLF: ::std::os::raw::c_int = 2;
pub const AL_BANDPASS_GAINHF: ::std::os::raw::c_int = 3;
pub const AL_FILTER_FIRST_PARAMETER: ::std::os::raw::c_int = 0;
pub const AL_FILTER_LAST_PARAMETER: ::std::os::raw::c_int = 32768;
pub const AL_FILTER_TYPE: ::std::os::raw::c_int = 32769;
pub const AL_FILTER_NULL: ::std::os::raw::c_int = 0;
pub const AL_FILTER_LOWPASS: ::std::os::raw::c_int = 1;
pub const AL_FILTER_HIGHPASS: ::std::os::raw::c_int = 2;
pub const AL_FILTER_BANDPASS: ::std::os::raw::c_int = 3;
pub const AL_REVERB_MIN_DECAY_HFLIMIT: ::std::os::raw::c_int = 0;
pub const AL_REVERB_MAX_DECAY_HFLIMIT: ::std::os::raw::c_int = 1;
pub const AL_REVERB_DEFAULT_DECAY_HFLIMIT: ::std::os::raw::c_int = 1;
pub const AL_EAXREVERB_MIN_DECAY_HFLIMIT: ::std::os::raw::c_int = 0;
pub const AL_EAXREVERB_MAX_DECAY_HFLIMIT: ::std::os::raw::c_int = 1;
pub const AL_EAXREVERB_DEFAULT_DECAY_HFLIMIT: ::std::os::raw::c_int = 1;
pub const AL_CHORUS_WAVEFORM_SINUSOID: ::std::os::raw::c_int = 0;
pub const AL_CHORUS_WAVEFORM_TRIANGLE: ::std::os::raw::c_int = 1;
pub const AL_CHORUS_MIN_WAVEFORM: ::std::os::raw::c_int = 0;
pub const AL_CHORUS_MAX_WAVEFORM: ::std::os::raw::c_int = 1;
pub const AL_CHORUS_DEFAULT_WAVEFORM: ::std::os::raw::c_int = 1;
pub const AL_CHORUS_MIN_PHASE: ::std::os::raw::c_int = -180;
pub const AL_CHORUS_MAX_PHASE: ::std::os::raw::c_int = 180;
pub const AL_CHORUS_DEFAULT_PHASE: ::std::os::raw::c_int = 90;
pub const AL_FLANGER_WAVEFORM_SINUSOID: ::std::os::raw::c_int = 0;
pub const AL_FLANGER_WAVEFORM_TRIANGLE: ::std::os::raw::c_int = 1;
pub const AL_FLANGER_MIN_WAVEFORM: ::std::os::raw::c_int = 0;
pub const AL_FLANGER_MAX_WAVEFORM: ::std::os::raw::c_int = 1;
pub const AL_FLANGER_DEFAULT_WAVEFORM: ::std::os::raw::c_int = 1;
pub const AL_FLANGER_MIN_PHASE: ::std::os::raw::c_int = -180;
pub const AL_FLANGER_MAX_PHASE: ::std::os::raw::c_int = 180;
pub const AL_FLANGER_DEFAULT_PHASE: ::std::os::raw::c_int = 0;
pub const AL_FREQUENCY_SHIFTER_MIN_LEFT_DIRECTION: ::std::os::raw::c_int = 0;
pub const AL_FREQUENCY_SHIFTER_MAX_LEFT_DIRECTION: ::std::os::raw::c_int = 2;
pub const AL_FREQUENCY_SHIFTER_DEFAULT_LEFT_DIRECTION: ::std::os::raw::c_int =
    0;
pub const AL_FREQUENCY_SHIFTER_DIRECTION_DOWN: ::std::os::raw::c_int = 0;
pub const AL_FREQUENCY_SHIFTER_DIRECTION_UP: ::std::os::raw::c_int = 1;
pub const AL_FREQUENCY_SHIFTER_DIRECTION_OFF: ::std::os::raw::c_int = 2;
pub const AL_FREQUENCY_SHIFTER_MIN_RIGHT_DIRECTION: ::std::os::raw::c_int = 0;
pub const AL_FREQUENCY_SHIFTER_MAX_RIGHT_DIRECTION: ::std::os::raw::c_int = 2;
pub const AL_FREQUENCY_SHIFTER_DEFAULT_RIGHT_DIRECTION: ::std::os::raw::c_int
          =
    0;
pub const AL_VOCAL_MORPHER_MIN_PHONEMEA: ::std::os::raw::c_int = 0;
pub const AL_VOCAL_MORPHER_MAX_PHONEMEA: ::std::os::raw::c_int = 29;
pub const AL_VOCAL_MORPHER_DEFAULT_PHONEMEA: ::std::os::raw::c_int = 0;
pub const AL_VOCAL_MORPHER_MIN_PHONEMEA_COARSE_TUNING: ::std::os::raw::c_int =
    -24;
pub const AL_VOCAL_MORPHER_MAX_PHONEMEA_COARSE_TUNING: ::std::os::raw::c_int =
    24;
pub const AL_VOCAL_MORPHER_DEFAULT_PHONEMEA_COARSE_TUNING:
          ::std::os::raw::c_int =
    0;
pub const AL_VOCAL_MORPHER_MIN_PHONEMEB: ::std::os::raw::c_int = 0;
pub const AL_VOCAL_MORPHER_MAX_PHONEMEB: ::std::os::raw::c_int = 29;
pub const AL_VOCAL_MORPHER_DEFAULT_PHONEMEB: ::std::os::raw::c_int = 10;
pub const AL_VOCAL_MORPHER_MIN_PHONEMEB_COARSE_TUNING: ::std::os::raw::c_int =
    -24;
pub const AL_VOCAL_MORPHER_MAX_PHONEMEB_COARSE_TUNING: ::std::os::raw::c_int =
    24;
pub const AL_VOCAL_MORPHER_DEFAULT_PHONEMEB_COARSE_TUNING:
          ::std::os::raw::c_int =
    0;
pub const AL_VOCAL_MORPHER_PHONEME_A: ::std::os::raw::c_int = 0;
pub const AL_VOCAL_MORPHER_PHONEME_E: ::std::os::raw::c_int = 1;
pub const AL_VOCAL_MORPHER_PHONEME_I: ::std::os::raw::c_int = 2;
pub const AL_VOCAL_MORPHER_PHONEME_O: ::std::os::raw::c_int = 3;
pub const AL_VOCAL_MORPHER_PHONEME_U: ::std::os::raw::c_int = 4;
pub const AL_VOCAL_MORPHER_PHONEME_AA: ::std::os::raw::c_int = 5;
pub const AL_VOCAL_MORPHER_PHONEME_AE: ::std::os::raw::c_int = 6;
pub const AL_VOCAL_MORPHER_PHONEME_AH: ::std::os::raw::c_int = 7;
pub const AL_VOCAL_MORPHER_PHONEME_AO: ::std::os::raw::c_int = 8;
pub const AL_VOCAL_MORPHER_PHONEME_EH: ::std::os::raw::c_int = 9;
pub const AL_VOCAL_MORPHER_PHONEME_ER: ::std::os::raw::c_int = 10;
pub const AL_VOCAL_MORPHER_PHONEME_IH: ::std::os::raw::c_int = 11;
pub const AL_VOCAL_MORPHER_PHONEME_IY: ::std::os::raw::c_int = 12;
pub const AL_VOCAL_MORPHER_PHONEME_UH: ::std::os::raw::c_int = 13;
pub const AL_VOCAL_MORPHER_PHONEME_UW: ::std::os::raw::c_int = 14;
pub const AL_VOCAL_MORPHER_PHONEME_B: ::std::os::raw::c_int = 15;
pub const AL_VOCAL_MORPHER_PHONEME_D: ::std::os::raw::c_int = 16;
pub const AL_VOCAL_MORPHER_PHONEME_F: ::std::os::raw::c_int = 17;
pub const AL_VOCAL_MORPHER_PHONEME_G: ::std::os::raw::c_int = 18;
pub const AL_VOCAL_MORPHER_PHONEME_J: ::std::os::raw::c_int = 19;
pub const AL_VOCAL_MORPHER_PHONEME_K: ::std::os::raw::c_int = 20;
pub const AL_VOCAL_MORPHER_PHONEME_L: ::std::os::raw::c_int = 21;
pub const AL_VOCAL_MORPHER_PHONEME_M: ::std::os::raw::c_int = 22;
pub const AL_VOCAL_MORPHER_PHONEME_N: ::std::os::raw::c_int = 23;
pub const AL_VOCAL_MORPHER_PHONEME_P: ::std::os::raw::c_int = 24;
pub const AL_VOCAL_MORPHER_PHONEME_R: ::std::os::raw::c_int = 25;
pub const AL_VOCAL_MORPHER_PHONEME_S: ::std::os::raw::c_int = 26;
pub const AL_VOCAL_MORPHER_PHONEME_T: ::std::os::raw::c_int = 27;
pub const AL_VOCAL_MORPHER_PHONEME_V: ::std::os::raw::c_int = 28;
pub const AL_VOCAL_MORPHER_PHONEME_Z: ::std::os::raw::c_int = 29;
pub const AL_VOCAL_MORPHER_WAVEFORM_SINUSOID: ::std::os::raw::c_int = 0;
pub const AL_VOCAL_MORPHER_WAVEFORM_TRIANGLE: ::std::os::raw::c_int = 1;
pub const AL_VOCAL_MORPHER_WAVEFORM_SAWTOOTH: ::std::os::raw::c_int = 2;
pub const AL_VOCAL_MORPHER_MIN_WAVEFORM: ::std::os::raw::c_int = 0;
pub const AL_VOCAL_MORPHER_MAX_WAVEFORM: ::std::os::raw::c_int = 2;
pub const AL_VOCAL_MORPHER_DEFAULT_WAVEFORM: ::std::os::raw::c_int = 0;
pub const AL_PITCH_SHIFTER_MIN_COARSE_TUNE: ::std::os::raw::c_int = -12;
pub const AL_PITCH_SHIFTER_MAX_COARSE_TUNE: ::std::os::raw::c_int = 12;
pub const AL_PITCH_SHIFTER_DEFAULT_COARSE_TUNE: ::std::os::raw::c_int = 12;
pub const AL_PITCH_SHIFTER_MIN_FINE_TUNE: ::std::os::raw::c_int = -50;
pub const AL_PITCH_SHIFTER_MAX_FINE_TUNE: ::std::os::raw::c_int = 50;
pub const AL_PITCH_SHIFTER_DEFAULT_FINE_TUNE: ::std::os::raw::c_int = 0;
pub const AL_RING_MODULATOR_SINUSOID: ::std::os::raw::c_int = 0;
pub const AL_RING_MODULATOR_SAWTOOTH: ::std::os::raw::c_int = 1;
pub const AL_RING_MODULATOR_SQUARE: ::std::os::raw::c_int = 2;
pub const AL_RING_MODULATOR_MIN_WAVEFORM: ::std::os::raw::c_int = 0;
pub const AL_RING_MODULATOR_MAX_WAVEFORM: ::std::os::raw::c_int = 2;
pub const AL_RING_MODULATOR_DEFAULT_WAVEFORM: ::std::os::raw::c_int = 0;
pub const AL_COMPRESSOR_MIN_ONOFF: ::std::os::raw::c_int = 0;
pub const AL_COMPRESSOR_MAX_ONOFF: ::std::os::raw::c_int = 1;
pub const AL_COMPRESSOR_DEFAULT_ONOFF: ::std::os::raw::c_int = 1;
pub const AL_MIN_DIRECT_FILTER_GAINHF_AUTO: ::std::os::raw::c_int = 0;
pub const AL_MAX_DIRECT_FILTER_GAINHF_AUTO: ::std::os::raw::c_int = 1;
pub const AL_DEFAULT_DIRECT_FILTER_GAINHF_AUTO: ::std::os::raw::c_int = 1;
pub const AL_MIN_AUXILIARY_SEND_FILTER_GAIN_AUTO: ::std::os::raw::c_int = 0;
pub const AL_MAX_AUXILIARY_SEND_FILTER_GAIN_AUTO: ::std::os::raw::c_int = 1;
pub const AL_DEFAULT_AUXILIARY_SEND_FILTER_GAIN_AUTO: ::std::os::raw::c_int =
    1;
pub const AL_MIN_AUXILIARY_SEND_FILTER_GAINHF_AUTO: ::std::os::raw::c_int = 0;
pub const AL_MAX_AUXILIARY_SEND_FILTER_GAINHF_AUTO: ::std::os::raw::c_int = 1;
pub const AL_DEFAULT_AUXILIARY_SEND_FILTER_GAINHF_AUTO: ::std::os::raw::c_int
          =
    1;
pub const ALC_EXT_disconnect: ::std::os::raw::c_int = 1;
pub const ALC_CONNECTED: ::std::os::raw::c_int = 787;
pub const ALC_EXT_thread_local_context: ::std::os::raw::c_int = 1;
pub const AL_EXT_source_distance_model: ::std::os::raw::c_int = 1;
pub const AL_SOURCE_DISTANCE_MODEL: ::std::os::raw::c_int = 512;
pub const AL_SOFT_buffer_sub_data: ::std::os::raw::c_int = 1;
pub const AL_BYTE_RW_OFFSETS_SOFT: ::std::os::raw::c_int = 4145;
pub const AL_SAMPLE_RW_OFFSETS_SOFT: ::std::os::raw::c_int = 4146;
pub const AL_SOFT_loop_points: ::std::os::raw::c_int = 1;
pub const AL_LOOP_POINTS_SOFT: ::std::os::raw::c_int = 8213;
pub const AL_EXT_FOLDBACK: ::std::os::raw::c_int = 1;
pub const AL_FOLDBACK_EVENT_BLOCK: ::std::os::raw::c_int = 16658;
pub const AL_FOLDBACK_EVENT_START: ::std::os::raw::c_int = 16657;
pub const AL_FOLDBACK_EVENT_STOP: ::std::os::raw::c_int = 16659;
pub const AL_FOLDBACK_MODE_MONO: ::std::os::raw::c_int = 16641;
pub const AL_FOLDBACK_MODE_STEREO: ::std::os::raw::c_int = 16642;
pub const ALC_EXT_DEDICATED: ::std::os::raw::c_int = 1;
pub const AL_DEDICATED_GAIN: ::std::os::raw::c_int = 1;
pub const AL_EFFECT_DEDICATED_DIALOGUE: ::std::os::raw::c_int = 36865;
pub const AL_EFFECT_DEDICATED_LOW_FREQUENCY_EFFECT: ::std::os::raw::c_int =
    36864;
pub const AL_SOFT_buffer_samples: ::std::os::raw::c_int = 1;
pub const AL_MONO_SOFT: ::std::os::raw::c_int = 5376;
pub const AL_STEREO_SOFT: ::std::os::raw::c_int = 5377;
pub const AL_REAR_SOFT: ::std::os::raw::c_int = 5378;
pub const AL_QUAD_SOFT: ::std::os::raw::c_int = 5379;
pub const AL_5POINT1_SOFT: ::std::os::raw::c_int = 5380;
pub const AL_6POINT1_SOFT: ::std::os::raw::c_int = 5381;
pub const AL_7POINT1_SOFT: ::std::os::raw::c_int = 5382;
pub const AL_BYTE_SOFT: ::std::os::raw::c_int = 5120;
pub const AL_UNSIGNED_BYTE_SOFT: ::std::os::raw::c_int = 5121;
pub const AL_SHORT_SOFT: ::std::os::raw::c_int = 5122;
pub const AL_UNSIGNED_SHORT_SOFT: ::std::os::raw::c_int = 5123;
pub const AL_INT_SOFT: ::std::os::raw::c_int = 5124;
pub const AL_UNSIGNED_INT_SOFT: ::std::os::raw::c_int = 5125;
pub const AL_FLOAT_SOFT: ::std::os::raw::c_int = 5126;
pub const AL_DOUBLE_SOFT: ::std::os::raw::c_int = 5127;
pub const AL_BYTE3_SOFT: ::std::os::raw::c_int = 5128;
pub const AL_UNSIGNED_BYTE3_SOFT: ::std::os::raw::c_int = 5129;
pub const AL_MONO8_SOFT: ::std::os::raw::c_int = 4352;
pub const AL_MONO16_SOFT: ::std::os::raw::c_int = 4353;
pub const AL_MONO32F_SOFT: ::std::os::raw::c_int = 65552;
pub const AL_STEREO8_SOFT: ::std::os::raw::c_int = 4354;
pub const AL_STEREO16_SOFT: ::std::os::raw::c_int = 4355;
pub const AL_STEREO32F_SOFT: ::std::os::raw::c_int = 65553;
pub const AL_QUAD8_SOFT: ::std::os::raw::c_int = 4612;
pub const AL_QUAD16_SOFT: ::std::os::raw::c_int = 4613;
pub const AL_QUAD32F_SOFT: ::std::os::raw::c_int = 4614;
pub const AL_REAR8_SOFT: ::std::os::raw::c_int = 4615;
pub const AL_REAR16_SOFT: ::std::os::raw::c_int = 4616;
pub const AL_REAR32F_SOFT: ::std::os::raw::c_int = 4617;
pub const AL_5POINT1_8_SOFT: ::std::os::raw::c_int = 4618;
pub const AL_5POINT1_16_SOFT: ::std::os::raw::c_int = 4619;
pub const AL_5POINT1_32F_SOFT: ::std::os::raw::c_int = 4620;
pub const AL_6POINT1_8_SOFT: ::std::os::raw::c_int = 4621;
pub const AL_6POINT1_16_SOFT: ::std::os::raw::c_int = 4622;
pub const AL_6POINT1_32F_SOFT: ::std::os::raw::c_int = 4623;
pub const AL_7POINT1_8_SOFT: ::std::os::raw::c_int = 4624;
pub const AL_7POINT1_16_SOFT: ::std::os::raw::c_int = 4625;
pub const AL_7POINT1_32F_SOFT: ::std::os::raw::c_int = 4626;
pub const AL_INTERNAL_FORMAT_SOFT: ::std::os::raw::c_int = 8200;
pub const AL_BYTE_LENGTH_SOFT: ::std::os::raw::c_int = 8201;
pub const AL_SAMPLE_LENGTH_SOFT: ::std::os::raw::c_int = 8202;
pub const AL_SEC_LENGTH_SOFT: ::std::os::raw::c_int = 8203;
pub const AL_SOFT_direct_channels: ::std::os::raw::c_int = 1;
pub const AL_DIRECT_CHANNELS_SOFT: ::std::os::raw::c_int = 4147;
pub const ALC_SOFT_loopback: ::std::os::raw::c_int = 1;
pub const ALC_FORMAT_CHANNELS_SOFT: ::std::os::raw::c_int = 6544;
pub const ALC_FORMAT_TYPE_SOFT: ::std::os::raw::c_int = 6545;
pub const ALC_BYTE_SOFT: ::std::os::raw::c_int = 5120;
pub const ALC_UNSIGNED_BYTE_SOFT: ::std::os::raw::c_int = 5121;
pub const ALC_SHORT_SOFT: ::std::os::raw::c_int = 5122;
pub const ALC_UNSIGNED_SHORT_SOFT: ::std::os::raw::c_int = 5123;
pub const ALC_INT_SOFT: ::std::os::raw::c_int = 5124;
pub const ALC_UNSIGNED_INT_SOFT: ::std::os::raw::c_int = 5125;
pub const ALC_FLOAT_SOFT: ::std::os::raw::c_int = 5126;
pub const ALC_MONO_SOFT: ::std::os::raw::c_int = 5376;
pub const ALC_STEREO_SOFT: ::std::os::raw::c_int = 5377;
pub const ALC_QUAD_SOFT: ::std::os::raw::c_int = 5379;
pub const ALC_5POINT1_SOFT: ::std::os::raw::c_int = 5380;
pub const ALC_6POINT1_SOFT: ::std::os::raw::c_int = 5381;
pub const ALC_7POINT1_SOFT: ::std::os::raw::c_int = 5382;
pub const AL_EXT_STEREO_ANGLES: ::std::os::raw::c_int = 1;
pub const AL_STEREO_ANGLES: ::std::os::raw::c_int = 4144;
pub const AL_EXT_SOURCE_RADIUS: ::std::os::raw::c_int = 1;
pub const AL_SOURCE_RADIUS: ::std::os::raw::c_int = 4145;
pub const AL_SOFT_source_latency: ::std::os::raw::c_int = 1;
pub const AL_SAMPLE_OFFSET_LATENCY_SOFT: ::std::os::raw::c_int = 4608;
pub const AL_SEC_OFFSET_LATENCY_SOFT: ::std::os::raw::c_int = 4609;
pub const ALC_EXT_DEFAULT_FILTER_ORDER: ::std::os::raw::c_int = 1;
pub const ALC_DEFAULT_FILTER_ORDER: ::std::os::raw::c_int = 4352;
pub const AL_SOFT_deferred_updates: ::std::os::raw::c_int = 1;
pub const AL_DEFERRED_UPDATES_SOFT: ::std::os::raw::c_int = 49154;
pub const AL_SOFT_block_alignment: ::std::os::raw::c_int = 1;
pub const AL_UNPACK_BLOCK_ALIGNMENT_SOFT: ::std::os::raw::c_int = 8204;
pub const AL_PACK_BLOCK_ALIGNMENT_SOFT: ::std::os::raw::c_int = 8205;
pub const AL_SOFT_MSADPCM: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_MONO_MSADPCM_SOFT: ::std::os::raw::c_int = 4866;
pub const AL_FORMAT_STEREO_MSADPCM_SOFT: ::std::os::raw::c_int = 4867;
pub const AL_SOFT_source_length: ::std::os::raw::c_int = 1;
pub const ALC_SOFT_pause_device: ::std::os::raw::c_int = 1;
pub const AL_EXT_BFORMAT: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_BFORMAT2D_8: ::std::os::raw::c_int = 131105;
pub const AL_FORMAT_BFORMAT2D_16: ::std::os::raw::c_int = 131106;
pub const AL_FORMAT_BFORMAT2D_FLOAT32: ::std::os::raw::c_int = 131107;
pub const AL_FORMAT_BFORMAT3D_8: ::std::os::raw::c_int = 131121;
pub const AL_FORMAT_BFORMAT3D_16: ::std::os::raw::c_int = 131122;
pub const AL_FORMAT_BFORMAT3D_FLOAT32: ::std::os::raw::c_int = 131123;
pub const AL_EXT_MULAW_BFORMAT: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_BFORMAT2D_MULAW: ::std::os::raw::c_int = 65585;
pub const AL_FORMAT_BFORMAT3D_MULAW: ::std::os::raw::c_int = 65586;
pub const ALC_SOFT_HRTF: ::std::os::raw::c_int = 1;
pub const ALC_HRTF_SOFT: ::std::os::raw::c_int = 6546;
pub const ALC_DONT_CARE_SOFT: ::std::os::raw::c_int = 2;
pub const ALC_HRTF_STATUS_SOFT: ::std::os::raw::c_int = 6547;
pub const ALC_HRTF_DISABLED_SOFT: ::std::os::raw::c_int = 0;
pub const ALC_HRTF_ENABLED_SOFT: ::std::os::raw::c_int = 1;
pub const ALC_HRTF_DENIED_SOFT: ::std::os::raw::c_int = 2;
pub const ALC_HRTF_REQUIRED_SOFT: ::std::os::raw::c_int = 3;
pub const ALC_HRTF_HEADPHONES_DETECTED_SOFT: ::std::os::raw::c_int = 4;
pub const ALC_HRTF_UNSUPPORTED_FORMAT_SOFT: ::std::os::raw::c_int = 5;
pub const ALC_NUM_HRTF_SPECIFIERS_SOFT: ::std::os::raw::c_int = 6548;
pub const ALC_HRTF_SPECIFIER_SOFT: ::std::os::raw::c_int = 6549;
pub const ALC_HRTF_ID_SOFT: ::std::os::raw::c_int = 6550;
pub const AL_SOFT_gain_clamp_ex: ::std::os::raw::c_int = 1;
pub const AL_GAIN_LIMIT_SOFT: ::std::os::raw::c_int = 8206;
pub type ptrdiff_t = isize;
pub type size_t = usize;
pub type wchar_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: ::std::os::raw::c_longlong,
    pub __clang_max_align_nonce2: f64,
}
impl ::std::default::Default for max_align_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type __int8_t = ::std::os::raw::c_char;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_longlong;
pub type __uint64_t = ::std::os::raw::c_ulonglong;
pub type __int_least8_t = __int8_t;
pub type __uint_least8_t = __uint8_t;
pub type __int_least16_t = __int16_t;
pub type __uint_least16_t = __uint16_t;
pub type __int_least32_t = __int32_t;
pub type __uint_least32_t = __uint32_t;
pub type __int_least64_t = __int64_t;
pub type __uint_least64_t = __uint64_t;
pub type __int_fast8_t = __int32_t;
pub type __uint_fast8_t = __uint32_t;
pub type __int_fast16_t = __int32_t;
pub type __uint_fast16_t = __uint32_t;
pub type __int_fast32_t = __int32_t;
pub type __uint_fast32_t = __uint32_t;
pub type __int_fast64_t = __int64_t;
pub type __uint_fast64_t = __uint64_t;
pub type __intptr_t = ::std::os::raw::c_int;
pub type __uintptr_t = ::std::os::raw::c_uint;
pub type __intmax_t = __int64_t;
pub type __uintmax_t = __uint64_t;
pub type __register_t = __int32_t;
pub type __vaddr_t = ::std::os::raw::c_ulong;
pub type __paddr_t = ::std::os::raw::c_ulong;
pub type __vsize_t = ::std::os::raw::c_ulong;
pub type __psize_t = ::std::os::raw::c_ulong;
pub type __clock_t = ::std::os::raw::c_int;
pub type __clockid_t = ::std::os::raw::c_int;
pub type __ptrdiff_t = ::std::os::raw::c_long;
pub type __time_t = ::std::os::raw::c_int;
pub type __timer_t = ::std::os::raw::c_int;
pub type __va_list = __builtin_va_list;
pub type __wchar_t = ::std::os::raw::c_int;
pub type __wint_t = ::std::os::raw::c_int;
pub type __rune_t = ::std::os::raw::c_int;
pub type __wctrans_t = *mut ::std::os::raw::c_void;
pub type __wctype_t = *mut ::std::os::raw::c_void;
pub type __cpuid_t = ::std::os::raw::c_ulong;
pub type __dev_t = __int32_t;
pub type __fixpt_t = __uint32_t;
pub type __gid_t = __uint32_t;
pub type __id_t = __uint32_t;
pub type __in_addr_t = __uint32_t;
pub type __in_port_t = __uint16_t;
pub type __ino_t = __uint32_t;
pub type __key_t = ::std::os::raw::c_long;
pub type __mode_t = __uint32_t;
pub type __nlink_t = __uint32_t;
pub type __pid_t = __int32_t;
pub type __rlim_t = __uint64_t;
pub type __sa_family_t = __uint16_t;
pub type __segsz_t = __int32_t;
pub type __socklen_t = __uint32_t;
pub type __swblk_t = __int32_t;
pub type __uid_t = __uint32_t;
pub type __useconds_t = __uint32_t;
pub type __suseconds_t = __int32_t;
#[repr(C)]
#[derive(Copy)]
pub struct __mbstate_t {
    pub _bindgen_data_: [u64; 16usize],
}
impl __mbstate_t {
    pub unsafe fn __mbstate8(&mut self)
     -> *mut [::std::os::raw::c_char; 128usize] {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __mbstateL(&mut self) -> *mut __int64_t {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
}
impl ::std::clone::Clone for __mbstate_t {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for __mbstate_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type int8_t = i8;
pub type uint8_t = u8;
pub type int16_t = i16;
pub type uint16_t = u16;
pub type int32_t = i32;
pub type uint32_t = u32;
pub type int64_t = i64;
pub type uint64_t = u64;
pub type int_least8_t = int8_t;
pub type int_fast8_t = int8_t;
pub type uint_least8_t = uint8_t;
pub type uint_fast8_t = uint8_t;
pub type int_least16_t = int16_t;
pub type int_fast16_t = int32_t;
pub type uint_least16_t = uint16_t;
pub type uint_fast16_t = uint32_t;
pub type int_least32_t = int32_t;
pub type int_fast32_t = int32_t;
pub type uint_least32_t = uint32_t;
pub type uint_fast32_t = uint32_t;
pub type int_least64_t = int64_t;
pub type int_fast64_t = int64_t;
pub type uint_least64_t = uint64_t;
pub type uint_fast64_t = uint64_t;
pub type intptr_t = isize;
pub type uintptr_t = usize;
pub type uintmax_t = uint64_t;
pub type intmax_t = int64_t;
pub type ssize_t = isize;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct imaxdiv_t {
    pub quot: intmax_t,
    pub rem: intmax_t,
}
impl ::std::default::Default for imaxdiv_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub enum ALCdevice_struct { }
pub type ALCdevice = ALCdevice_struct;
pub enum ALCcontext_struct { }
pub type ALCcontext = ALCcontext_struct;
pub type ALCboolean = ::std::os::raw::c_char;
pub type ALCchar = ::std::os::raw::c_char;
pub type ALCbyte = ::std::os::raw::c_char;
pub type ALCubyte = ::std::os::raw::c_uchar;
pub type ALCshort = ::std::os::raw::c_short;
pub type ALCushort = ::std::os::raw::c_ushort;
pub type ALCint = ::std::os::raw::c_int;
pub type ALCuint = ::std::os::raw::c_uint;
pub type ALCsizei = ::std::os::raw::c_int;
pub type ALCenum = ::std::os::raw::c_int;
pub type ALCfloat = f32;
pub type ALCdouble = f64;
pub type ALCvoid = ::std::os::raw::c_void;
pub type LPALCCREATECONTEXT =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice,
                                               attrlist: *const ALCint)
                              -> *mut ALCcontext>;
pub type LPALCMAKECONTEXTCURRENT =
    ::std::option::Option<unsafe extern "C" fn(context: *mut ALCcontext)
                              -> ALCboolean>;
pub type LPALCPROCESSCONTEXT =
    ::std::option::Option<unsafe extern "C" fn(context: *mut ALCcontext)>;
pub type LPALCSUSPENDCONTEXT =
    ::std::option::Option<unsafe extern "C" fn(context: *mut ALCcontext)>;
pub type LPALCDESTROYCONTEXT =
    ::std::option::Option<unsafe extern "C" fn(context: *mut ALCcontext)>;
pub type LPALCGETCURRENTCONTEXT =
    ::std::option::Option<extern "C" fn() -> *mut ALCcontext>;
pub type LPALCGETCONTEXTSDEVICE =
    ::std::option::Option<unsafe extern "C" fn(context: *mut ALCcontext)
                              -> *mut ALCdevice>;
pub type LPALCOPENDEVICE =
    ::std::option::Option<unsafe extern "C" fn(devicename: *const ALCchar)
                              -> *mut ALCdevice>;
pub type LPALCCLOSEDEVICE =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice)
                              -> ALCboolean>;
pub type LPALCGETERROR =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice)
                              -> ALCenum>;
pub type LPALCISEXTENSIONPRESENT =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice,
                                               extname: *const ALCchar)
                              -> ALCboolean>;
pub type LPALCGETPROCADDRESS =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice,
                                               funcname: *const ALCchar)
                              -> *mut ::std::os::raw::c_void>;
pub type LPALCGETENUMVALUE =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice,
                                               enumname: *const ALCchar)
                              -> ALCenum>;
pub type LPALCGETSTRING =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice,
                                               param: ALCenum)
                              -> *const ALCchar>;
pub type LPALCGETINTEGERV =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice,
                                               param: ALCenum, size: ALCsizei,
                                               values: *mut ALCint)>;
pub type LPALCCAPTUREOPENDEVICE =
    ::std::option::Option<unsafe extern "C" fn(devicename: *const ALCchar,
                                               frequency: ALCuint,
                                               format: ALCenum,
                                               buffersize: ALCsizei)
                              -> *mut ALCdevice>;
pub type LPALCCAPTURECLOSEDEVICE =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice)
                              -> ALCboolean>;
pub type LPALCCAPTURESTART =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice)>;
pub type LPALCCAPTURESTOP =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice)>;
pub type LPALCCAPTURESAMPLES =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice,
                                               buffer: *mut ALCvoid,
                                               samples: ALCsizei)>;
pub type ALboolean = ::std::os::raw::c_char;
pub type ALchar = ::std::os::raw::c_char;
pub type ALbyte = ::std::os::raw::c_char;
pub type ALubyte = ::std::os::raw::c_uchar;
pub type ALshort = ::std::os::raw::c_short;
pub type ALushort = ::std::os::raw::c_ushort;
pub type ALint = ::std::os::raw::c_int;
pub type ALuint = ::std::os::raw::c_uint;
pub type ALsizei = ::std::os::raw::c_int;
pub type ALenum = ::std::os::raw::c_int;
pub type ALfloat = f32;
pub type ALdouble = f64;
pub type ALvoid = ::std::os::raw::c_void;
pub type LPALENABLE =
    ::std::option::Option<extern "C" fn(capability: ALenum)>;
pub type LPALDISABLE =
    ::std::option::Option<extern "C" fn(capability: ALenum)>;
pub type LPALISENABLED =
    ::std::option::Option<extern "C" fn(capability: ALenum) -> ALboolean>;
pub type LPALGETSTRING =
    ::std::option::Option<extern "C" fn(param: ALenum) -> *const ALchar>;
pub type LPALGETBOOLEANV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               values: *mut ALboolean)>;
pub type LPALGETINTEGERV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               values: *mut ALint)>;
pub type LPALGETFLOATV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               values: *mut ALfloat)>;
pub type LPALGETDOUBLEV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               values: *mut ALdouble)>;
pub type LPALGETBOOLEAN =
    ::std::option::Option<extern "C" fn(param: ALenum) -> ALboolean>;
pub type LPALGETINTEGER =
    ::std::option::Option<extern "C" fn(param: ALenum) -> ALint>;
pub type LPALGETFLOAT =
    ::std::option::Option<extern "C" fn(param: ALenum) -> ALfloat>;
pub type LPALGETDOUBLE =
    ::std::option::Option<extern "C" fn(param: ALenum) -> ALdouble>;
pub type LPALGETERROR = ::std::option::Option<extern "C" fn() -> ALenum>;
pub type LPALISEXTENSIONPRESENT =
    ::std::option::Option<unsafe extern "C" fn(extname: *const ALchar)
                              -> ALboolean>;
pub type LPALGETPROCADDRESS =
    ::std::option::Option<unsafe extern "C" fn(fname: *const ALchar)
                              -> *mut ::std::os::raw::c_void>;
pub type LPALGETENUMVALUE =
    ::std::option::Option<unsafe extern "C" fn(ename: *const ALchar)
                              -> ALenum>;
pub type LPALLISTENERF =
    ::std::option::Option<extern "C" fn(param: ALenum, value: ALfloat)>;
pub type LPALLISTENER3F =
    ::std::option::Option<extern "C" fn(param: ALenum, value1: ALfloat,
                                        value2: ALfloat, value3: ALfloat)>;
pub type LPALLISTENERFV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               values: *const ALfloat)>;
pub type LPALLISTENERI =
    ::std::option::Option<extern "C" fn(param: ALenum, value: ALint)>;
pub type LPALLISTENER3I =
    ::std::option::Option<extern "C" fn(param: ALenum, value1: ALint,
                                        value2: ALint, value3: ALint)>;
pub type LPALLISTENERIV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               values: *const ALint)>;
pub type LPALGETLISTENERF =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               value: *mut ALfloat)>;
pub type LPALGETLISTENER3F =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               value1: *mut ALfloat,
                                               value2: *mut ALfloat,
                                               value3: *mut ALfloat)>;
pub type LPALGETLISTENERFV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               values: *mut ALfloat)>;
pub type LPALGETLISTENERI =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               value: *mut ALint)>;
pub type LPALGETLISTENER3I =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               value1: *mut ALint,
                                               value2: *mut ALint,
                                               value3: *mut ALint)>;
pub type LPALGETLISTENERIV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum,
                                               values: *mut ALint)>;
pub type LPALGENSOURCES =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei,
                                               sources: *mut ALuint)>;
pub type LPALDELETESOURCES =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei,
                                               sources: *const ALuint)>;
pub type LPALISSOURCE =
    ::std::option::Option<extern "C" fn(source: ALuint) -> ALboolean>;
pub type LPALSOURCEF =
    ::std::option::Option<extern "C" fn(source: ALuint, param: ALenum,
                                        value: ALfloat)>;
pub type LPALSOURCE3F =
    ::std::option::Option<extern "C" fn(source: ALuint, param: ALenum,
                                        value1: ALfloat, value2: ALfloat,
                                        value3: ALfloat)>;
pub type LPALSOURCEFV =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum,
                                               values: *const ALfloat)>;
pub type LPALSOURCEI =
    ::std::option::Option<extern "C" fn(source: ALuint, param: ALenum,
                                        value: ALint)>;
pub type LPALSOURCE3I =
    ::std::option::Option<extern "C" fn(source: ALuint, param: ALenum,
                                        value1: ALint, value2: ALint,
                                        value3: ALint)>;
pub type LPALSOURCEIV =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum,
                                               values: *const ALint)>;
pub type LPALGETSOURCEF =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum,
                                               value: *mut ALfloat)>;
pub type LPALGETSOURCE3F =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum,
                                               value1: *mut ALfloat,
                                               value2: *mut ALfloat,
                                               value3: *mut ALfloat)>;
pub type LPALGETSOURCEFV =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum,
                                               values: *mut ALfloat)>;
pub type LPALGETSOURCEI =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum,
                                               value: *mut ALint)>;
pub type LPALGETSOURCE3I =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum,
                                               value1: *mut ALint,
                                               value2: *mut ALint,
                                               value3: *mut ALint)>;
pub type LPALGETSOURCEIV =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum,
                                               values: *mut ALint)>;
pub type LPALSOURCEPLAYV =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei,
                                               sources: *const ALuint)>;
pub type LPALSOURCESTOPV =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei,
                                               sources: *const ALuint)>;
pub type LPALSOURCEREWINDV =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei,
                                               sources: *const ALuint)>;
pub type LPALSOURCEPAUSEV =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei,
                                               sources: *const ALuint)>;
pub type LPALSOURCEPLAY =
    ::std::option::Option<extern "C" fn(source: ALuint)>;
pub type LPALSOURCESTOP =
    ::std::option::Option<extern "C" fn(source: ALuint)>;
pub type LPALSOURCEREWIND =
    ::std::option::Option<extern "C" fn(source: ALuint)>;
pub type LPALSOURCEPAUSE =
    ::std::option::Option<extern "C" fn(source: ALuint)>;
pub type LPALSOURCEQUEUEBUFFERS =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, nb: ALsizei,
                                               buffers: *const ALuint)>;
pub type LPALSOURCEUNQUEUEBUFFERS =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, nb: ALsizei,
                                               buffers: *mut ALuint)>;
pub type LPALGENBUFFERS =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei,
                                               buffers: *mut ALuint)>;
pub type LPALDELETEBUFFERS =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei,
                                               buffers: *const ALuint)>;
pub type LPALISBUFFER =
    ::std::option::Option<extern "C" fn(buffer: ALuint) -> ALboolean>;
pub type LPALBUFFERDATA =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, format: ALenum,
                                               data: *const ALvoid,
                                               size: ALsizei, freq: ALsizei)>;
pub type LPALBUFFERF =
    ::std::option::Option<extern "C" fn(buffer: ALuint, param: ALenum,
                                        value: ALfloat)>;
pub type LPALBUFFER3F =
    ::std::option::Option<extern "C" fn(buffer: ALuint, param: ALenum,
                                        value1: ALfloat, value2: ALfloat,
                                        value3: ALfloat)>;
pub type LPALBUFFERFV =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum,
                                               values: *const ALfloat)>;
pub type LPALBUFFERI =
    ::std::option::Option<extern "C" fn(buffer: ALuint, param: ALenum,
                                        value: ALint)>;
pub type LPALBUFFER3I =
    ::std::option::Option<extern "C" fn(buffer: ALuint, param: ALenum,
                                        value1: ALint, value2: ALint,
                                        value3: ALint)>;
pub type LPALBUFFERIV =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum,
                                               values: *const ALint)>;
pub type LPALGETBUFFERF =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum,
                                               value: *mut ALfloat)>;
pub type LPALGETBUFFER3F =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum,
                                               value1: *mut ALfloat,
                                               value2: *mut ALfloat,
                                               value3: *mut ALfloat)>;
pub type LPALGETBUFFERFV =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum,
                                               values: *mut ALfloat)>;
pub type LPALGETBUFFERI =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum,
                                               value: *mut ALint)>;
pub type LPALGETBUFFER3I =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum,
                                               value1: *mut ALint,
                                               value2: *mut ALint,
                                               value3: *mut ALint)>;
pub type LPALGETBUFFERIV =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum,
                                               values: *mut ALint)>;
pub type LPALDOPPLERFACTOR =
    ::std::option::Option<extern "C" fn(value: ALfloat)>;
pub type LPALDOPPLERVELOCITY =
    ::std::option::Option<extern "C" fn(value: ALfloat)>;
pub type LPALSPEEDOFSOUND =
    ::std::option::Option<extern "C" fn(value: ALfloat)>;
pub type LPALDISTANCEMODEL =
    ::std::option::Option<extern "C" fn(distanceModel: ALenum)>;
pub type PFNALBUFFERDATASTATICPROC =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALint, arg2: ALenum,
                                               arg3: *mut ALvoid,
                                               arg4: ALsizei, arg5: ALsizei)
                              -> ALvoid>;
pub type LPALGENEFFECTS =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALsizei,
                                               arg2: *mut ALuint)>;
pub type LPALDELETEEFFECTS =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALsizei,
                                               arg2: *const ALuint)>;
pub type LPALISEFFECT =
    ::std::option::Option<extern "C" fn(arg1: ALuint) -> ALboolean>;
pub type LPALEFFECTI =
    ::std::option::Option<extern "C" fn(arg1: ALuint, arg2: ALenum,
                                        arg3: ALint)>;
pub type LPALEFFECTIV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *const ALint)>;
pub type LPALEFFECTF =
    ::std::option::Option<extern "C" fn(arg1: ALuint, arg2: ALenum,
                                        arg3: ALfloat)>;
pub type LPALEFFECTFV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *const ALfloat)>;
pub type LPALGETEFFECTI =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALint)>;
pub type LPALGETEFFECTIV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALint)>;
pub type LPALGETEFFECTF =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALfloat)>;
pub type LPALGETEFFECTFV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALfloat)>;
pub type LPALGENFILTERS =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALsizei,
                                               arg2: *mut ALuint)>;
pub type LPALDELETEFILTERS =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALsizei,
                                               arg2: *const ALuint)>;
pub type LPALISFILTER =
    ::std::option::Option<extern "C" fn(arg1: ALuint) -> ALboolean>;
pub type LPALFILTERI =
    ::std::option::Option<extern "C" fn(arg1: ALuint, arg2: ALenum,
                                        arg3: ALint)>;
pub type LPALFILTERIV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *const ALint)>;
pub type LPALFILTERF =
    ::std::option::Option<extern "C" fn(arg1: ALuint, arg2: ALenum,
                                        arg3: ALfloat)>;
pub type LPALFILTERFV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *const ALfloat)>;
pub type LPALGETFILTERI =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALint)>;
pub type LPALGETFILTERIV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALint)>;
pub type LPALGETFILTERF =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALfloat)>;
pub type LPALGETFILTERFV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALfloat)>;
pub type LPALGENAUXILIARYEFFECTSLOTS =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALsizei,
                                               arg2: *mut ALuint)>;
pub type LPALDELETEAUXILIARYEFFECTSLOTS =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALsizei,
                                               arg2: *const ALuint)>;
pub type LPALISAUXILIARYEFFECTSLOT =
    ::std::option::Option<extern "C" fn(arg1: ALuint) -> ALboolean>;
pub type LPALAUXILIARYEFFECTSLOTI =
    ::std::option::Option<extern "C" fn(arg1: ALuint, arg2: ALenum,
                                        arg3: ALint)>;
pub type LPALAUXILIARYEFFECTSLOTIV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *const ALint)>;
pub type LPALAUXILIARYEFFECTSLOTF =
    ::std::option::Option<extern "C" fn(arg1: ALuint, arg2: ALenum,
                                        arg3: ALfloat)>;
pub type LPALAUXILIARYEFFECTSLOTFV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *const ALfloat)>;
pub type LPALGETAUXILIARYEFFECTSLOTI =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALint)>;
pub type LPALGETAUXILIARYEFFECTSLOTIV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALint)>;
pub type LPALGETAUXILIARYEFFECTSLOTF =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALfloat)>;
pub type LPALGETAUXILIARYEFFECTSLOTFV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALfloat)>;
pub type PFNALCSETTHREADCONTEXTPROC =
    ::std::option::Option<unsafe extern "C" fn(context: *mut ALCcontext)
                              -> ALCboolean>;
pub type PFNALCGETTHREADCONTEXTPROC =
    ::std::option::Option<extern "C" fn() -> *mut ALCcontext>;
pub type PFNALBUFFERSUBDATASOFTPROC =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *const ALvoid,
                                               arg4: ALsizei, arg5: ALsizei)
                              -> ALvoid>;
pub type LPALFOLDBACKCALLBACK =
    ::std::option::Option<extern "C" fn(arg1: ALenum, arg2: ALsizei)>;
pub type LPALREQUESTFOLDBACKSTART =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALenum, arg2: ALsizei,
                                               arg3: ALsizei,
                                               arg4: *mut ALfloat,
                                               arg5: LPALFOLDBACKCALLBACK)>;
pub type LPALREQUESTFOLDBACKSTOP = ::std::option::Option<extern "C" fn()>;
pub type LPALBUFFERSAMPLESSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALuint,
                                               arg3: ALenum, arg4: ALsizei,
                                               arg5: ALenum, arg6: ALenum,
                                               arg7: *const ALvoid)>;
pub type LPALBUFFERSUBSAMPLESSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALsizei,
                                               arg3: ALsizei, arg4: ALenum,
                                               arg5: ALenum,
                                               arg6: *const ALvoid)>;
pub type LPALGETBUFFERSAMPLESSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALsizei,
                                               arg3: ALsizei, arg4: ALenum,
                                               arg5: ALenum,
                                               arg6: *mut ALvoid)>;
pub type LPALISBUFFERFORMATSUPPORTEDSOFT =
    ::std::option::Option<extern "C" fn(arg1: ALenum) -> ALboolean>;
pub type LPALCLOOPBACKOPENDEVICESOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: *const ALCchar)
                              -> *mut ALCdevice>;
pub type LPALCISRENDERFORMATSUPPORTEDSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: *mut ALCdevice,
                                               arg2: ALCsizei, arg3: ALCenum,
                                               arg4: ALCenum) -> ALCboolean>;
pub type LPALCRENDERSAMPLESSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: *mut ALCdevice,
                                               arg2: *mut ALCvoid,
                                               arg3: ALCsizei)>;
pub type ALint64SOFT = int64_t;
pub type ALuint64SOFT = uint64_t;
pub type LPALSOURCEDSOFT =
    ::std::option::Option<extern "C" fn(arg1: ALuint, arg2: ALenum,
                                        arg3: ALdouble)>;
pub type LPALSOURCE3DSOFT =
    ::std::option::Option<extern "C" fn(arg1: ALuint, arg2: ALenum,
                                        arg3: ALdouble, arg4: ALdouble,
                                        arg5: ALdouble)>;
pub type LPALSOURCEDVSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *const ALdouble)>;
pub type LPALGETSOURCEDSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALdouble)>;
pub type LPALGETSOURCE3DSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALdouble,
                                               arg4: *mut ALdouble,
                                               arg5: *mut ALdouble)>;
pub type LPALGETSOURCEDVSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALdouble)>;
pub type LPALSOURCEI64SOFT =
    ::std::option::Option<extern "C" fn(arg1: ALuint, arg2: ALenum,
                                        arg3: ALint64SOFT)>;
pub type LPALSOURCE3I64SOFT =
    ::std::option::Option<extern "C" fn(arg1: ALuint, arg2: ALenum,
                                        arg3: ALint64SOFT, arg4: ALint64SOFT,
                                        arg5: ALint64SOFT)>;
pub type LPALSOURCEI64VSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *const ALint64SOFT)>;
pub type LPALGETSOURCEI64SOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALint64SOFT)>;
pub type LPALGETSOURCE3I64SOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALint64SOFT,
                                               arg4: *mut ALint64SOFT,
                                               arg5: *mut ALint64SOFT)>;
pub type LPALGETSOURCEI64VSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALint64SOFT)>;
pub type LPALDEFERUPDATESSOFT =
    ::std::option::Option<extern "C" fn() -> ALvoid>;
pub type LPALPROCESSUPDATESSOFT =
    ::std::option::Option<extern "C" fn() -> ALvoid>;
pub type LPALCDEVICEPAUSESOFT =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice)>;
pub type LPALCDEVICERESUMESOFT =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice)>;
pub type LPALCGETSTRINGISOFT =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice,
                                               paramName: ALCenum,
                                               index: ALCsizei)
                              -> *const ALCchar>;
pub type LPALCRESETDEVICESOFT =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice,
                                               attribs: *const ALCint)
                              -> ALCboolean>;
pub type __builtin_va_list = [__va_list_tag; 1usize];
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct __va_list_tag {
    pub gp_offset: ::std::os::raw::c_uint,
    pub fp_offset: ::std::os::raw::c_uint,
    pub overflow_arg_area: *mut ::std::os::raw::c_void,
    pub reg_save_area: *mut ::std::os::raw::c_void,
}
impl ::std::default::Default for __va_list_tag {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[link(name = "openal", kind = "dylib")]
extern "C" {
    pub fn strtoimax(arg1: *const ::std::os::raw::c_char,
                     arg2: *mut *mut ::std::os::raw::c_char,
                     arg3: ::std::os::raw::c_int) -> intmax_t;
    pub fn strtoumax(arg1: *const ::std::os::raw::c_char,
                     arg2: *mut *mut ::std::os::raw::c_char,
                     arg3: ::std::os::raw::c_int) -> uintmax_t;
    pub fn strntoimax(nptr: *const ::std::os::raw::c_char,
                      endptr: *mut *mut ::std::os::raw::c_char,
                      base: ::std::os::raw::c_int, n: size_t) -> intmax_t;
    pub fn strntoumax(nptr: *const ::std::os::raw::c_char,
                      endptr: *mut *mut ::std::os::raw::c_char,
                      base: ::std::os::raw::c_int, n: size_t) -> uintmax_t;
    pub fn alcCreateContext(device: *mut ALCdevice, attrlist: *const ALCint)
     -> *mut ALCcontext;
    pub fn alcMakeContextCurrent(context: *mut ALCcontext) -> ALCboolean;
    pub fn alcProcessContext(context: *mut ALCcontext);
    pub fn alcSuspendContext(context: *mut ALCcontext);
    pub fn alcDestroyContext(context: *mut ALCcontext);
    pub fn alcGetCurrentContext() -> *mut ALCcontext;
    pub fn alcGetContextsDevice(context: *mut ALCcontext) -> *mut ALCdevice;
    pub fn alcOpenDevice(devicename: *const ALCchar) -> *mut ALCdevice;
    pub fn alcCloseDevice(device: *mut ALCdevice) -> ALCboolean;
    pub fn alcGetError(device: *mut ALCdevice) -> ALCenum;
    pub fn alcIsExtensionPresent(device: *mut ALCdevice,
                                 extname: *const ALCchar) -> ALCboolean;
    pub fn alcGetProcAddress(device: *mut ALCdevice, funcname: *const ALCchar)
     -> *mut ::std::os::raw::c_void;
    pub fn alcGetEnumValue(device: *mut ALCdevice, enumname: *const ALCchar)
     -> ALCenum;
    pub fn alcGetString(device: *mut ALCdevice, param: ALCenum)
     -> *const ALCchar;
    pub fn alcGetIntegerv(device: *mut ALCdevice, param: ALCenum,
                          size: ALCsizei, values: *mut ALCint);
    pub fn alcCaptureOpenDevice(devicename: *const ALCchar,
                                frequency: ALCuint, format: ALCenum,
                                buffersize: ALCsizei) -> *mut ALCdevice;
    pub fn alcCaptureCloseDevice(device: *mut ALCdevice) -> ALCboolean;
    pub fn alcCaptureStart(device: *mut ALCdevice);
    pub fn alcCaptureStop(device: *mut ALCdevice);
    pub fn alcCaptureSamples(device: *mut ALCdevice, buffer: *mut ALCvoid,
                             samples: ALCsizei);
    pub fn alDopplerFactor(value: ALfloat);
    pub fn alDopplerVelocity(value: ALfloat);
    pub fn alSpeedOfSound(value: ALfloat);
    pub fn alDistanceModel(distanceModel: ALenum);
    pub fn alEnable(capability: ALenum);
    pub fn alDisable(capability: ALenum);
    pub fn alIsEnabled(capability: ALenum) -> ALboolean;
    pub fn alGetString(param: ALenum) -> *const ALchar;
    pub fn alGetBooleanv(param: ALenum, values: *mut ALboolean);
    pub fn alGetIntegerv(param: ALenum, values: *mut ALint);
    pub fn alGetFloatv(param: ALenum, values: *mut ALfloat);
    pub fn alGetDoublev(param: ALenum, values: *mut ALdouble);
    pub fn alGetBoolean(param: ALenum) -> ALboolean;
    pub fn alGetInteger(param: ALenum) -> ALint;
    pub fn alGetFloat(param: ALenum) -> ALfloat;
    pub fn alGetDouble(param: ALenum) -> ALdouble;
    pub fn alGetError() -> ALenum;
    pub fn alIsExtensionPresent(extname: *const ALchar) -> ALboolean;
    pub fn alGetProcAddress(fname: *const ALchar)
     -> *mut ::std::os::raw::c_void;
    pub fn alGetEnumValue(ename: *const ALchar) -> ALenum;
    pub fn alListenerf(param: ALenum, value: ALfloat);
    pub fn alListener3f(param: ALenum, value1: ALfloat, value2: ALfloat,
                        value3: ALfloat);
    pub fn alListenerfv(param: ALenum, values: *const ALfloat);
    pub fn alListeneri(param: ALenum, value: ALint);
    pub fn alListener3i(param: ALenum, value1: ALint, value2: ALint,
                        value3: ALint);
    pub fn alListeneriv(param: ALenum, values: *const ALint);
    pub fn alGetListenerf(param: ALenum, value: *mut ALfloat);
    pub fn alGetListener3f(param: ALenum, value1: *mut ALfloat,
                           value2: *mut ALfloat, value3: *mut ALfloat);
    pub fn alGetListenerfv(param: ALenum, values: *mut ALfloat);
    pub fn alGetListeneri(param: ALenum, value: *mut ALint);
    pub fn alGetListener3i(param: ALenum, value1: *mut ALint,
                           value2: *mut ALint, value3: *mut ALint);
    pub fn alGetListeneriv(param: ALenum, values: *mut ALint);
    pub fn alGenSources(n: ALsizei, sources: *mut ALuint);
    pub fn alDeleteSources(n: ALsizei, sources: *const ALuint);
    pub fn alIsSource(source: ALuint) -> ALboolean;
    pub fn alSourcef(source: ALuint, param: ALenum, value: ALfloat);
    pub fn alSource3f(source: ALuint, param: ALenum, value1: ALfloat,
                      value2: ALfloat, value3: ALfloat);
    pub fn alSourcefv(source: ALuint, param: ALenum, values: *const ALfloat);
    pub fn alSourcei(source: ALuint, param: ALenum, value: ALint);
    pub fn alSource3i(source: ALuint, param: ALenum, value1: ALint,
                      value2: ALint, value3: ALint);
    pub fn alSourceiv(source: ALuint, param: ALenum, values: *const ALint);
    pub fn alGetSourcef(source: ALuint, param: ALenum, value: *mut ALfloat);
    pub fn alGetSource3f(source: ALuint, param: ALenum, value1: *mut ALfloat,
                         value2: *mut ALfloat, value3: *mut ALfloat);
    pub fn alGetSourcefv(source: ALuint, param: ALenum, values: *mut ALfloat);
    pub fn alGetSourcei(source: ALuint, param: ALenum, value: *mut ALint);
    pub fn alGetSource3i(source: ALuint, param: ALenum, value1: *mut ALint,
                         value2: *mut ALint, value3: *mut ALint);
    pub fn alGetSourceiv(source: ALuint, param: ALenum, values: *mut ALint);
    pub fn alSourcePlayv(n: ALsizei, sources: *const ALuint);
    pub fn alSourceStopv(n: ALsizei, sources: *const ALuint);
    pub fn alSourceRewindv(n: ALsizei, sources: *const ALuint);
    pub fn alSourcePausev(n: ALsizei, sources: *const ALuint);
    pub fn alSourcePlay(source: ALuint);
    pub fn alSourceStop(source: ALuint);
    pub fn alSourceRewind(source: ALuint);
    pub fn alSourcePause(source: ALuint);
    pub fn alSourceQueueBuffers(source: ALuint, nb: ALsizei,
                                buffers: *const ALuint);
    pub fn alSourceUnqueueBuffers(source: ALuint, nb: ALsizei,
                                  buffers: *mut ALuint);
    pub fn alGenBuffers(n: ALsizei, buffers: *mut ALuint);
    pub fn alDeleteBuffers(n: ALsizei, buffers: *const ALuint);
    pub fn alIsBuffer(buffer: ALuint) -> ALboolean;
    pub fn alBufferData(buffer: ALuint, format: ALenum, data: *const ALvoid,
                        size: ALsizei, freq: ALsizei);
    pub fn alBufferf(buffer: ALuint, param: ALenum, value: ALfloat);
    pub fn alBuffer3f(buffer: ALuint, param: ALenum, value1: ALfloat,
                      value2: ALfloat, value3: ALfloat);
    pub fn alBufferfv(buffer: ALuint, param: ALenum, values: *const ALfloat);
    pub fn alBufferi(buffer: ALuint, param: ALenum, value: ALint);
    pub fn alBuffer3i(buffer: ALuint, param: ALenum, value1: ALint,
                      value2: ALint, value3: ALint);
    pub fn alBufferiv(buffer: ALuint, param: ALenum, values: *const ALint);
    pub fn alGetBufferf(buffer: ALuint, param: ALenum, value: *mut ALfloat);
    pub fn alGetBuffer3f(buffer: ALuint, param: ALenum, value1: *mut ALfloat,
                         value2: *mut ALfloat, value3: *mut ALfloat);
    pub fn alGetBufferfv(buffer: ALuint, param: ALenum, values: *mut ALfloat);
    pub fn alGetBufferi(buffer: ALuint, param: ALenum, value: *mut ALint);
    pub fn alGetBuffer3i(buffer: ALuint, param: ALenum, value1: *mut ALint,
                         value2: *mut ALint, value3: *mut ALint);
    pub fn alGetBufferiv(buffer: ALuint, param: ALenum, values: *mut ALint);
}
